### ISSUE TITLE
Romania - programtv.ele.ro

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#10]
@Robinmcgvr the above website stopped on Kablam on 10th April 2020.  Is this something yourself and Matteo are aware of?  This is used for the following Romanian channels:-
PRIMA
PROTV
TVR1
TVR2
KANALD
AXN

**Comment by Robinmcgvr** [comment]
@Lynne12 
Re. recovering data for programtv.ele.ro - it is not looking very promising - the url takes us to ele.ro now and there is no apparent tv guide on the site.

I have found a new site and asked Matteo to see if he can get this one to work, there will be no back data from that source though.
Good-ish news is that we have all the channels covered by individual channel sites apart from Kanal D and Axn i think.
I am also asking Matteo to download data from those 2 channel sites as a back up source .

I know loading different channels from different sites is a pain in the neck - so it may be easier to get that missing chunk of data manually scheduled from the single channel kapow sources .

**Comment by Lynne12** [comment]
@Robinmcgvr can you let me know once you have worked out if there is a single replacement site, please, so that I know what date range is missing.  Manually scheduling all these channels, for the gaps will take too long, as they are not film only channels.  It may be that we have to set up all the channels to load the gaps on the online scheduling, but will wait until the final missing situation is known.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Will do, I am just waiting to hear back from Matteo whether he can pull data from the new site I found.

**Comment by Robinmcgvr** [comment]
@Lynne12 
we have a new site for Romania cinemagia.ro
This has only just started though . 
Axn.ro is fixed too, just a slight hitch that the data is going into poland folder, I have asked Matteo to fix that.
Still leaves us with a gap for kanal D but nothing we can do about that now

**Comment by Lynne12** [comment]
@Robinmcgvr can you confirm what date cinemagia.ro will be running from please?

**Comment by Robinmcgvr** [comment]
@Lynne12 
First day is 3rd May

**Comment by Lynne12** [comment]
@Robinmcgvr please advise once cinemagia.ro is available on Kablam and the full list of channels it will be used for (from the programtv.ele.ro that was previously used). I have checked today and it is not there currently. In addition axn.ro is not on Kablam.

**Comment by Robinmcgvr** [comment]
I have requested that Richard add the site to Kablam

**Comment by Lynne12** [comment]
I also need confirmation of which channels, from my list above it will be supplying?

**Comment by Robinmcgvr** [comment]
These are the channels we are pulling, so I guess all of them?
Kanal D
--
AXN
Prima TV
Pro TV
TVr 1
Tvr 2
Antena 1
Pro 2

**Comment by Robinmcgvr** [comment]
But it's your choice at the end of the day as to which channels we load from where, whatever is easiest for you.

**Comment by Lynne12** [comment]
Prima is missing for 27th & 28th April, from the replacement website (for gap filling) primatv.ro.

**Comment by Lynne12** [comment]
> @Lynne12
> we have a new site for Romania cinemagia.ro
> This has only just started though .
> Axn.ro is fixed too, just a slight hitch that the data is going into poland folder, I have asked Matteo to fix that.
> Still leaves us with a gap for kanal D but nothing we can do about that now

@Robinmcgvr will need axn.ro on Kablam too please.

**Comment by Robinmcgvr** [comment]
@Lynne12 
The axn.ro data has been moved back to Romania folder now.
I have asked Richard to add the relevant sites to Kablam , so hopefully that won't be too long.
I will let you know if we get data for Prima for 27th and 28th , but I am not hopeful.
It may take a few days to give a final answer on that.

**Comment by Lynne12** [comment]
@Robinmcgvr in line with your email from Matteo, it would be good to get all the sites that used to be supplied by ele.ro on to Matteo's suggested website, programetv.program24.ro.  That way we are not messing about with multiple sites and as Matteo advised we can go back on this replacement website.  I will wait to hear before doing any more on Romania.

**Comment by Lynne12** [comment]
I have requested Richard to add the program24.ro site to Kablam.

**Comment by Lynne12** [comment]
> @Robinmcgvr in line with your email from Matteo, it would be good to get all the sites that used to be supplied by ele.ro on to Matteo's suggested website, programetv.program24.ro. That way we are not messing about with multiple sites and as Matteo advised we can go back on this replacement website. I will wait to hear before doing any more on Romania.

@Robinmcgvr a couple of questions:-

1.  Have you heard from Matteo on this?
2.  The gap filling site, for AXN (axn.ro), does not have data from 11-26 April, so I have only been able to load 27th April onwards.

**Comment by Robinmcgvr** [comment]
It would be better if we were able to proceed with the other Romanian channels in the meantime as we don't need axn for Paramount .
I will see what Matteo can do with the data from program24 , but I think it is better to proceed with what we have and drop the one channel in later, rather than delaying all Romanian data.

**Comment by Lynne12** [comment]
All data that can be loaded has been.  I also need the new site for Kanal D, so you will be missing that too until it is set up.  Until we have the new site I am having to manually pull all the other channels, which is time consuming.  Once the new site is set up it will download weekly automatically.  I have spent a lot of time, over the past few working days gap filling all the online scheduling countries that have issues, which is not ideal when there is a new site (in this case), which will solve that problem.

**Comment by Robinmcgvr** [comment]
Yep we are all running around trying to fix the data myself and Matteo included.;
It would be good of course if Richard were able to make this process less complicated then the substitutions would be easier to do.
But that may be wishful thinking!

**Comment by Lynne12** [comment]
Just to confirm the current situation for April (a reminder to me as much as anybody else).  The following channels still have missing data, for April:-
AXN - 11-26 April
KANAL D - 11-30 April and going forwards (no source yet set up)

**Comment by Lynne12** [comment]
Awaiting Richard to set up programetv.program24.ro on Kablam, so that the gaps in the above two channels can be loaded.

**Comment by Lynne12** [comment]
@Robinmcgvr has Matteo confirmed that this data is now okay, from 17th May onwards?  Your email 22 May refers to this.

**Comment by Lynne12** [comment]
Missing dates for April have now all been loaded.
