### ISSUE TITLE
Portugal - nos.pt

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#101]
@Robinmcgvr data missing for 19th September

**Comment by Robinmcgvr** [comment]
Yes this has been reported

**Comment by Robinmcgvr** [comment]
data has not been recovered

**Comment by Robinmcgvr** [comment]
We didn't get this back so we'll have to use the other sources, prob easier to manually schedule that one day then mess about with loader - I'll try and get that done

**Comment by Lynne12** [comment]
Thanks, can you update here, if you do get that scheduled.

**Comment by Robinmcgvr** [comment]
Done
