### ISSUE TITLE
Switzerland - teleclub

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#102]
@Robinmcgvr data missing 16-20 September 2021

**Comment by Robinmcgvr** [comment]
@Lynne12 - Reported to Matteo

**Comment by Robinmcgvr** [comment]
This site looks like it has ceased and we need to set up a new one https://tv.blue.ch/tv-guide
In the meantime we should be able to get the required channels from tvsearch.ch, where they are under the names teleclub Action and Teleclub Prime'.

**Comment by Robinmcgvr** [comment]
This is still being worked on

**Comment by Lynne12** [comment]
21-27 September also missing.

**Comment by Robinmcgvr** [comment]
See above

**Comment by Robinmcgvr** [comment]
Matteo has now set up the new robot for site blue.ch - We need to get Richard to add it to Kablam etc.
depending on how long that takes, there is the alternative source available 'tvsearch.ch'

**Comment by Lynne12** [comment]
Will hang fire for now, as we still have August scheduling to be worked on.

**Comment by Lynne12** [comment]
For reference, total date range now missing is 16 September - 4 October 2021.

**Comment by Robinmcgvr** [comment]
@Lynne12 
The site has ceased but the new source blue.ch is now available covering data back to September 1st

**Comment by Robinmcgvr** [comment]
Site been added to Kablam so you should be able to proceed with this now

**Comment by Lynne12** [comment]
Richard has been requested to set up new website on the data loader, after which time I shall load the missing date ranges for both channels.

**Comment by Lynne12** [comment]
Data loaded.

**Comment by Lynne12** [comment]
@Robinmcgvr can you please confirm which channel relates to TCBZ (Teleclub) and which to TCBS (Teleclub Star) on the blue.ch website, on Kablam please.

**Comment by Lynne12** [comment]
@Robinmcgvr any answer on this, please.  I believe the data may be loaded on the wrong channels and I need to rectify it, if necessary, for September and October data.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Sorry never saw your earlier message think it got lost among the dozens of emails flooding the inbox - am checking for you now

**Comment by Robinmcgvr** [comment]
This is what we said back in April 'TCBZ=blue Prime and TCBS=blue Action'
does this not look right now?

**Comment by Lynne12** [comment]
That's what I have too.  I think Richard has set up the wrong Kablam source to the wrong ETS channel.  I will get it switched.  This is for data from 16 September, when we made the loading source switch.

**Comment by Robinmcgvr** [comment]
Oh dear, how annoying, at least it's only very recent data affected.

**Comment by Lynne12** [comment]
Yes, luckily Branko picked it up and it hasn't been worked on.
