### ISSUE TITLE
Sweden - viasat.se

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#103]
@Lynne12 
Another site that is now redirecting elsewhere , but there is no data on the redirected site.
Data for channel V film premiere is available from tv-tabla.se
It is probably going to best to switch to that source for loading as this may take a while to sort itself out.

**Comment by Lynne12** [comment]
@Robinmcgvr I have made the website switch.

**Comment by Robinmcgvr** [comment]
we are pulling data from this site again now but we are still missing a chunk, so it is probably best to stick to the alternative you switched to unless this turns out to be unsatisfactory.
