### ISSUE TITLE
TAIWAN - fng.tw

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#104]
@Lynne12 
fng.tw seems to have ceased as of the 28th Sept - a bit of a disaster!
There seems to be a new version called dng.tw - I have alerted Matteo and asked him to try and grab this one instead.
Fingers crossed this will work!

**Comment by Lynne12** [comment]
Let me know when this is ready, as I will need to make changes to the Data loader.

**Comment by Robinmcgvr** [comment]
@Lynne12 
We have data from the new source going back to 1st September 
I have asked Richard to add it to Kablam - It may be that because this site has a slightly different format to the fng.tw that we may be able to load Star Movies HD data in english now which would be nice!

**Comment by Lynne12** [comment]
@Robinmcgvr is there any update on this, please?

**Comment by Robinmcgvr** [comment]
Data is in Kablam and ready to go - starts from 01/09/2021

**Comment by Robinmcgvr** [comment]
We have the star movies HD in english now - and it is called smithhd in the new source

**Comment by Lynne12** [comment]
@Robinmcgvr before I get Richard to set this up Kablam has the channel listed as smithd, as oppose to smithhd from your comment above.  Can you please confirm which it is please?

**Comment by Robinmcgvr** [comment]
smithd is the one

**Comment by Lynne12** [comment]
@Robinmcgvr just to confirm that from 28th September 2021 data we will no longer need the SMHD translations list.

**Comment by Robinmcgvr** [comment]
Further to that, could we could load the data for Fox Movies Taiwan too maybe?
That would mean Taiwan would need to be set up for online scheduling I realise... what do you think?
Debbie could still work on it if you don't want to give it to the schedulers ...

**Comment by Lynne12** [comment]
Sounds good.  There is a lot of work on that channel for manual scheduling.  I will give it to the schedulers, as they have lost several channels with the changeover of some Czech and some Romania to verified.  Let me know if this is to go ahead.

**Comment by Lynne12** [comment]
@Robinmcgvr could you prepare the SMHD for 1-27 September 2021 please.  I have just allocated this country to the schedulers, as they are nearing the end of August online scheduling.

**Comment by Robinmcgvr** [comment]
Cool the plan to give the schedulers Taiwan Fox Movies is a go from me.
I will get that SMHD done today or tomorrow.

**Comment by Lynne12** [comment]
@Robinmcgvr can you just confirm that these are the correct channel details, for Taiwan Fox Movies, taken from Kablam:-


**dngtw.tw | foxmovies**

**Comment by Robinmcgvr** [comment]
yep that is correct but n.b. in studio the channel is still called STAR MOVIES

**Comment by Lynne12** [comment]
I have asked Richard to set this up and will load data from 1st September once it is ready.

**Comment by Lynne12** [comment]
@Robinmcgvr data loaded, from 1st September 2021.  Can you confirm that we will still only need to translate FF and TM for this channel?

**Comment by Robinmcgvr** [comment]
Yes I can confirm that
I used to edit out the series when i prepped the data - there seem to be phases of series getting shown on this channel. Often there are none ,but some months there are.

**Comment by Robinmcgvr** [comment]
Another factor in this data is that the last airing of the day will have zero mins. this was the case before too, but I used to adjsut this in the data. If you could ask the inputters to change the air times of these as they go along that would be most useful.

**Comment by Lynne12** [comment]
They should do this as a matter of course, as they would with other zero minute durations, but I will let them know to keep an eye out, when I allocate this out for the first time.  This issue can be closed now?

**Comment by Robinmcgvr** [comment]
Yep, cheers
