### ISSUE TITLE
Hong Kong - epg.i-cable.com - online scheduling loading week 28 Sep - 4 Oct 2021

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#109]
@Robinmcgvr various dates missing for all channels for date range, 29th September - 4th October.

**Comment by Robinmcgvr** [comment]
ok thanks, the days are all there but i can see the file size changed, I shall investigate

**Comment by Robinmcgvr** [comment]
Ah as I suspected the channels have ceased to air, this is part of the Disney switch over to streaming
https://tbivision.com/2021/04/28/disney-to-close-18-channels-in-asia-as-streaming-focus-expands/
So we can drop these channels - but keep SMHD and the Taiwan still seem to be happening but as Star channels

**Comment by Lynne12** [comment]
@Robinmcgvr please confirm which channels are to remain for Hong Kong online scheduling and which can be dropped, please.

**Comment by Robinmcgvr** [comment]
Well we can't schedule the ones that no longer exist and we can those that do!
So TVB , Star Movies HD we keep doing

**Comment by Robinmcgvr** [comment]
We should do the channels as far as the data goes - so up to end of september

**Comment by Lynne12** [comment]
> Well we can't schedule the ones that no longer exist and we can those that do! So TVB , Star Movies HD we keep doing

Thanks for the response, although I don't think the tone was necessary.  I was asking a civil question, which you were able to answer easily, without me having to do a lot of research.

**Comment by Lynne12** [comment]
epg.i-cable removed from online scheduling, for the following channels:-

STAR WORLD (Fox Life)
STAR MOVIES (Fox Movies) (STMO)
NAT GEO
FOX FAMILY MOVIES
FAX ACTION MOVIES
