### ISSUE TITLE
Serbia - tvprofil.com

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#11]
@Lynne12 

We are currently missing 21 April - 4 May from this source.
Hopefully we will be able to recover it, it was reported last week, but seems not to have been fixed yet.

**Comment by Lynne12** [comment]
@Robinmcgvr thanks for the heads up.  I will be loading that week Wed/Thurs this week, so will check then.

**Comment by Lynne12** [comment]
@Robinmcgvr this also applies to the Serbian channels from this website.

**Comment by Robinmcgvr** [comment]
@Lynne12
Thanks both were reported to Matteo earlier this week

**Comment by Robinmcgvr** [comment]
@Lynne12
Luckily we have a back up site for Serbia mojtv.net which also covers Croatia

**Comment by Robinmcgvr** [comment]
@Lynne12 
We are still having issues with TVprofil. it should be OK for Croatia, but the site might not be listing all the Pink channels we use for Serbia.
Luckily we have good alternative sources for both

**Comment by Lynne12** [comment]
@Robinmcgvr still not okay for Croatia?  Nothing past early hours of 21st April, nor for any of the Serbian channels.

**Comment by Lynne12** [comment]
@Robinmcgvr can you confirm when they are up and running please, if they will be at some stage.  I have looked at mojtv and it does not cover RTL2, Croatia.  It will be messy to have lots of alternate sites set up, if they are only to be temporary and I can keep this as one of these as the last countries to schedule, in April, to allow more time for a permanent solution.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Perhaps you could take a look at the kapow files yourself?
I am a bit busy today .
I will look further when I have finished the high proirity tasks that I have to deal with

**Comment by Lynne12** [comment]
I already had done, which is why I was reporting to you, in response to you saying the site was now okay for Croatia. I haven't asked you to look today, was just merely responding to your information.  I can liaise directly with Matteo, if that is what you prefer, but in the past you have said only one person should deal with him on an issue, hence you set up this Github.

**Comment by Robinmcgvr** [comment]
I am unable to answer your question I am afraid. But it looks unlikely that the site will regain the missing channels, as some channels seem to be no longer available from tvprofil therefore I recommend shifting to the alternative data sources.

**Comment by Lynne12** [comment]
Not all channels are covered on the alternate source that you gave.  My previous note will confirm that.  I can use it for the ones that are.

**Comment by Robinmcgvr** [comment]
I have had some time now to look at these sources and channels :
I would suggest we use either the rtl.hr site or tvhr.net for rtl channels as these sources are giving us episode numbers .
tvhr.net also covers HRT 1 & 2
mojtv.net is a bit lacking in episode info so novatv site maybe better for the Nova channel
It may then be better to stick to using these three for loading for quality of data 
It's not ideal I know for you to have to use multiple sources but for the sake of the data it is probably best. There is no guarantee that we will be able to recover lost data, so I wouldn't wait for it.

**Comment by Lynne12** [comment]
@Robinmcgvr requested Richard to change from tvprofil.com to 3 alternate sites, for Croatia. Can you please confirm the replacement site(s) for Serbian channels.

**Comment by Lynne12** [comment]
> @Robinmcgvr requested Richard to change from tvprofil.com to 3 alternate sites, for Croatia. Can you please confirm the replacement site(s) for Serbian channels.

@Robinmcgvr do you have any news on this please?

**Comment by Lynne12** [comment]
Croatian replacment websites are now up and running and data has been loaded to fill the missing gaps.  This remains open for Serbia only now.

**Comment by Robinmcgvr** [comment]
mojtv.net was the recommended replacement site for Serbia

**Comment by Lynne12** [comment]
@Robinmcgvr this does not have Pink Kids channel.

**Comment by Robinmcgvr** [comment]
@Lynne12 
We will have to use tv.aladin.info for that one then. Bit of a nause, sorry

**Comment by Lynne12** [comment]
@Robinmcgvr will use these two new websites to fill the gaps and going forwards.
