### ISSUE TITLE
Greece - nova.gr

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#111]
@Lynne12 
19-21 Oct missing
Matteo Alerted

**Comment by Robinmcgvr** [comment]
Matteo working on this , will let you know when data is ready

**Comment by Robinmcgvr** [comment]
@Lynne12 
Data not been recovered, restarted 25,26 but now no 28 and 29th :-(

**Comment by Robinmcgvr** [comment]
new robot has been set up for this source - data available to 31/10/2021
BUT still gaps from 19-25 and 28th also missing
I could manually schedule the 28th if that doesn't mess things up for you with the loading .. data will not be available for long though, couple of days maybe,
We have Matteo working on a big job re. Czech data so that is why i am suggesting covering that day's data

**Comment by Robinmcgvr** [comment]
Ah better news on this now the channel nova cinema 1 is covered by tvepg.eu too
So we can get the data one way or another from there, I will ask Matteo to set this up for Greece, although may take a while, but at least we can recover the lost data from this source and fill our gap!

**Comment by Lynne12** [comment]
Email from @JonathanETS 24th November.  Stop working on channel from 2022.

**Comment by Lynne12** [comment]
I am loading data that is available from nova.gr for the following dates, 26, 27, 29, 30, 31 October.
