### ISSUE TITLE
Germany-tvtv.de

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#115]
@Robinmcgvr 13th November is missing.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Been reported to Matteo, will let you know when it's been recovered, should be doable.

**Comment by Robinmcgvr** [comment]
@Lynne12 
13th and 14 now recovered

**Comment by Lynne12** [comment]
13th loaded.  14th was already there and not missing when I pulled the files last week.

**Comment by Lynne12** [comment]
Data is still not available for ETS channel BAYN - Kablam Channel - BR Fernsehen

**Comment by Robinmcgvr** [comment]
Ah I see what you mean, most of 13th for BR missing, unfortunately we can't go back to that any more.
We can however fill in the gap via data from tvmovie.de 
I will put a note on the November scheduling that I need to do that.

**Comment by Lynne12** [comment]
@Robinmcgvr 5th December is missing.

**Comment by Robinmcgvr** [comment]
Thanks this was reported to Matteo , seems he recovered the 6th but not the 5th
On the plus side I think the channels we pull from this source may well be redundant for our clients apart from
BR - I can't find any of the other channels in a client list
We have BR data ( & HR, MDR, WDR SWR,NDR , ) in prisma.de - nothing found to enter on BR for this date
so I think we can get away with missing this day's data .

**Comment by Lynne12** [comment]
> Thanks this was reported to Matteo , seems he recovered the 6th but not the 5th On the plus side I think the channels we pull from this source may well be redundant for our clients apart from BR - I can't find any of the other channels in a client list We have BR data ( & HR, MDR, WDR SWR,NDR , ) in prisma.de - nothing found to enter on BR for this date so I think we can get away with missing this day's data .

@JonathanETS can you confirm if we are needing to continue with any of the following channels, in light of Robin's comment?
The channels we currently schedule are:-

- [x] 3SAT
- [x] BAYN 
- [ ] HES3
- [ ] MDRG
- [ ] NRD3
- [ ] RBB
- [ ] SUDW
- [ ] WST3

**Comment by Robinmcgvr** [comment]
We do still want BAYN (BR) & 3SAT

**Comment by JonathanETS** [comment]
Yes...  we need to keep  **BR Fernsehen**   and  **3Sat**.

Drop the others...  I used to cover them for Apra and CSCS...  but both of these are now ad hoc.   

Good call.  

I suppose we are so close to the end of the year that we could keep doing them for the remainder of 2021.   But they are LOW priority...  they should not get in the way of processing other stuff.

**Comment by Robinmcgvr** [comment]
tvtv.de 5-6 december now recovered

**Comment by Lynne12** [comment]
Issue needs to remain open until I load the data, otherwise it will get missed.

**Comment by Lynne12** [comment]
5th December loaded.  6th was not missing when I loaded data last week.

**Comment by Lynne12** [comment]
@Robinmcgvr 17th December 2021 missing.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Data still missing but not too much of an issue

**Comment by Lynne12** [comment]
I have manually scheduled 17th December for Bayern, from tvmovie.de, as this is the channel that will continue in 2022.

**Comment by Lynne12** [comment]
@Robinmcgvr 19th January 2022 missing.

**Comment by Robinmcgvr** [comment]
@Lynne12 
We'll have to cover this via tvmovie.de I am afraid

**Comment by Lynne12** [comment]
Nothing to schedule for Bayn on 19th December, using tvmovie.de.

**Comment by Lynne12** [comment]
@Robinmcgvr 26th January 2022 missing.

**Comment by Lynne12** [comment]
I've manually scheduled this from tvmovie.de
