### ISSUE TITLE
Netherlands - tvgids.nl

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#118]
@Robinmcgvr data stops on Kablam early hours 23 December 2021.  This is needed for CANN channel. Kablam channel name:

Film 1 Premiere

**Comment by Robinmcgvr** [comment]
We can cover this from Film.nl - Film 1Premiere.
I will see what can be done about the tvgids.nl site
But we have options if we can't recover it

**Comment by Robinmcgvr** [comment]
Spoke to JB as he uses data from the site Film.nl for some of his reports.
We both think that it would be worth shifting to using this source for loading.
let me know if there are any reasons you know of why this wouldn't be good to do. I know there are variations in data on film1.nl and tvgids.nl but the film1 site ought to be a better bet.

**Comment by Lynne12** [comment]
@Robinmcgvr I know we had problems with film.nl a long time ago, hence the switch to tvgids.nl.  Please confirm if you definately want to switch back?

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ok thanks I have looked at the data and I can see that yes there are issues with data from film.nl , the early hours airings are getting matched to the wrong day .
So we are prob better off sticking with tvgids.nl, however Matteo has only been able to recover data from 2nd Jan - leaving us a gap.
I have seen that the channel 1premiere (as it is now known) is available from the tvepg.eu site , so I will ask Matteo to add the channel to that source so we do have an alternative source for it going forwards.
Currently I can access data for 1premiere on tvepg.eu back to the 23rd december. I will ask if Matteo can grab data going back to there.
If not we'll have to either print out and manually schedule it or use the Film1 source for the period 23/12 to 01/01 and I can manually adjust the dates/ timings for those early hours airings .
I am not in the office today so I can't do any printing currently.
I'll save the first few days to pdf for now.

**Comment by Robinmcgvr** [comment]
The good news is we have fil1 data from tvepg.eu from 23/12 - 12/01
The bad news - only visible in Kablam from11/01 ?
I don't know what is going on here, I'll see if there is any change tomorrow as sometimes there is a lag in these things
