### ISSUE TITLE
Taiwan - dngtw.tw

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#119]
@Robinmcgvr Star Movies is missing 31st December 2021 - 3 January 2022.

**Comment by Robinmcgvr** [comment]
@Lynne12 
I've looked into this and the channel has rebranded to 'Star Movies Gold'

**Comment by Robinmcgvr** [comment]
Also looks like the Fox channel has gone back to being 'Star World' - more relevant for the manual scheduling side, but logging here for now
