### ISSUE TITLE
Netherlands - tvgids.nl

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#12]
@Robinmcgvr not sure if this has been raised with Matteo before.  Each day there is a film in the early hours of the morning, with a long duration.  When you look at an independent TV guide, rather than Kablam, this film actually shows the following day (although the time of the TV guide is an hour different in this case.  Is there anything that can be done about this from Matteo's end, as this causes quite a bit of manual adjustment when processing the channel?

CANN | 18/03/20 | 03:25 | 05:30 | **1565** |   | WARSCHAU '44

https://tvepg.eu/de/netherlands/channel/film1_premiere/2020-03-1

**Comment by Robinmcgvr** [comment]
@Lynne12 

Hi Lynne,

Hmm, that is a strange one.
I can see now that the end time is linking to the following day, so yes something is going wrong in the formatting here.
I will ask Matteo to look at what is happening here and if he can fix it fingers crossed!

**Comment by Lynne12** [comment]
@Robinmcgvr thank you.  Just to be clear the programme should be showing the day after it is appearing in Kablam, so it is the date that is actually wrong, but the fact that it is linking to the next day is then causing the long duration.

**Comment by Lynne12** [comment]
@Robinmcgvr I have manually adjusted all the March entries, but this may have been going back some time.

**Comment by Lynne12** [comment]
@Robinmcgvr is there any news from Matteo on this, please?

**Comment by Robinmcgvr** [comment]
@Lynne12 
He is still working on it.

**Comment by Robinmcgvr** [comment]
we have another source for the channel, if required, film1.nl - this is already in kablam.

**Comment by Lynne12** [comment]
@Robinmcgvr I believe we switched from that one some time ago, as there were issues with it, so will continue to wait on Matteo for a fix.

**Comment by Lynne12** [comment]
@Robinmcgvr is there any news on this yet, please?

**Comment by Lynne12** [comment]
@Robinmcgvr can you please give an update on this, from Matteo?  It is very time consuming manually changing these programmes each month.

**Comment by Robinmcgvr** [comment]
@Lynne12 
What's the date you last loaded data from?
I am pulling data in Kablam now to see if the data is alright now or not.

**Comment by Lynne12** [comment]
With the June data it looks like the long durations have stopped.  However, this has been replaced by another problem.  The early morning slot is now being duplicated, one with a '0' duration and the same start and end time and another with the correct duration:-

**STUDIO**
CANN | 04/06/20 | 02:40 |  02:40  | 0 |   | OFFICER DOWN

CANN | 04/06/20 | 02:40 | 04:20 | 100 |   | OFFICER DOWN

**KABLAM**

Jun 4, 2020 | 02:40 | 02:40 | tvgids.nl | Film 1 Premiere |   | Officer Down

Jun 4, 2020 | 02:40 | 04:20 | tvgids.nl | Film 1 Premiere |   | Officer Down



This happens daily.  Technically the inputter can delete the zero duration entry, but if it can be fixed that would be preferable.

**Comment by Robinmcgvr** [comment]
@Lynne12 
I think we are going to be stuck with that issue , I see it in the data now , there are quite a few of our channels that have a record like that where there is a zero mins followed by correct time . This should get fixed in checking even if missed by inputters.
So I would say go ahead and load.
