### ISSUE TITLE
Ireland online scheduling - tvguide.co.uk

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#121]
@Robinmcgvr the 4 Irish channels are missing on Kablam from 20th January 2022 onwards:-

RTE1
RTE2
TV3I
TG4

**Comment by Robinmcgvr** [comment]
@Lynne12 
I have referred this to Matteo, it seems the file size of data we grab from this source reduced dramatically after the data failure on the 20th Jan. I'll keep you posted on what he is able to reinstate.
Whilst we can use the Irish sites to fill in this data we obviously want to be able to get as much as we can from tvguide.co.uk as it's such a good source for so many channels

**Comment by Robinmcgvr** [comment]
Matteo working on this, not sure if we will be able to recover lost data though

**Comment by Lynne12** [comment]
@Robinmcgvr the following are missing for the week 8-14 February 2022:-

RTE1, RTE2 and TG4 missing 8-12 February
TV3 missing 8-14 February 2022

**Comment by Robinmcgvr** [comment]
@Lynne12 
We're still missing Virgin Media One data from this source. Not sure if we are going to be able to get that back.
RTE1 and 2 and TG4 are back in the downloads.
We'll have to use rte.ie or entertainment.ie to plug the gaps.
I am going to see if we can add another site to cover the virgin media 1 (TV3) as a back up

**Comment by Lynne12** [comment]
@Robinmcgvr Virgin Media One is on entertainment.ie.  I am going to use this for the gap filling for all 4 channels.  Shall I change Virgin Media One permanently to this website?

**Comment by Lynne12** [comment]
Data loaded as follows:-

RTE1, RTE2, TG4 - 20 January 2022 - 12 February 2022
TV3 - 20 January 2022 - 21 February 2022
