### ISSUE TITLE
Spain online scheduling - movistarplus.es

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#122]
@Robinmcgvr CAPS (#0) is missing from 19th January 2022 onwards.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Good news on this one, the channel has changed on movistar to m+ #0 - which is in kablam from 19/01/2022

**Comment by Lynne12** [comment]
Excellent.  I will get it changed on the loader.
