### ISSUE TITLE
Sweden-tv-tabla.se

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#123]
@Robinmcgvr data is missing for 8-19 February 2022

**Comment by Robinmcgvr** [comment]
Thanks this was reported on monday to Matteo, but he obviously hasn't fixed it yet

**Comment by Robinmcgvr** [comment]
@Lynne12 
The downloads are working again but Matteo was unable to recover missing data.
The data we need should be available via viasat.se

**Comment by Lynne12** [comment]
Data loaded, 8-19 February from viasat.se
