### ISSUE TITLE
PORTUGAL NOS.PT

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#127]
We have had a couple of days where only partial data has downloaded from this site. 
1) 13/02/2022
2) 01/03/2022

**Comment by Robinmcgvr** [comment]
I am asking Matteo if he can recover the 1st March but the 13th feb will have to be covered from one of the alternative Kablam sources

**Comment by Lynne12** [comment]
13th February is now loaded and will be translated by Branko.

**Comment by Robinmcgvr** [comment]
1st March data now recovered

**Comment by Lynne12** [comment]
@Robinmcgvr thanks.  This can now be closed.  I will be loading 1-7 March data later this week, so the 1st March will be loaded at this time.

**Comment by Robinmcgvr** [comment]
@Lynne12 
There was a problem with the 6th March data, so hold off on loading that week, for a couple of days, until Matteo fixes it.

**Comment by Lynne12** [comment]
@Robinmcgvr thanks.  Will wait to get the go ahead.

**Comment by Robinmcgvr** [comment]
If it doesn't get recovered in time, we can use tv.sapo.pt to fill in the gaps. (better than sic.sapo.pt)
nos.pt site is not in a printable format any more

**Comment by Robinmcgvr** [comment]
6th march now recovered

**Comment by Lynne12** [comment]
1-7 March loaded.
