### ISSUE TITLE
Czech Republic - hbo.cz

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#13]
@Robinmcgvr this site is missing from 25th April 2020, used to load HBO channel.  Is Matteo aware?

**Comment by Robinmcgvr** [comment]
Yes this was reported.
I am unable to @ respond to you, do you need to assign yourself?

**Comment by Lynne12** [comment]
I shouldn't need to as I created the issue.  There are others where I am not assigned.  It's @Lynne12

**Comment by Robinmcgvr** [comment]
@Lynne12
dunno nothing comes up, when do @ in normal way, maybe because I am at home
I manually typed it this time,anyway you are getting the messages so that's the important thing.
This was reported last week

**Comment by Robinmcgvr** [comment]
@Lynne12
Matteo is working on a lot of stuff at the moment, but I will do a bit more research into the site and whether missing data is likely to be recoverable

**Comment by Robinmcgvr** [comment]
Czech site does not allow us to go back , so I have given Matteo a nudge to work on this and the Hungarian site

**Comment by Robinmcgvr** [comment]
@Lynne12

It may be best to add the channel to Dawn's daily manual scheduling until we can get either the old site working again or a new one I have just sent to Matteo.

**Comment by Robinmcgvr** [comment]
@Lynne12

url  = hbogo.cz/program
or mujtvprogram.cz/TV-program-HBO#page_TvProgramTimeLine

**Comment by Robinmcgvr** [comment]
@Lynne12

Did you ask Dawn to do this scheduling?

**Comment by Robinmcgvr** [comment]
@Lyyne12
I have entered today's data - it would be good if we could get data entered up to and including Monday - let me know if no-one is available to do it

**Comment by Lynne12** [comment]
I haven't done so, no. We shouldn't really be adding channels to manual scheduling, as it is the most time consuming. Will wait on Matteo to confirm the new site is up and running. There are websites with this data on that go back, for temporary gap filling:-
http://tvprogram.centrum.cz/den/2020/4/25/

**Comment by Lynne12** [comment]
Data loaded to fill gaps from centrum.cz

**Comment by Lynne12** [comment]
@Robinmcgvr data missing 5-9 May.  I will fill the gaps from centrum.cz again, but do we have any word from Matteo on the new website?
