### ISSUE TITLE
Spain-movistarplus.es

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#130]
@Robinmcgvr the above website is missing for the week 8-14 March 2022.  This is used for CAPS  and was previously listed as M+ #0

**Comment by Robinmcgvr** [comment]
yes thanks I am aware and it was reported to Matteo.
I had thought, incorrectly that we had dropped the channel, which is why i didn't report to you.

**Comment by Robinmcgvr** [comment]
If you don't want to wait for Matteo to set up a new robot for the changed URL (why it's failing) you can use elmundo.es

**Comment by Lynne12** [comment]
If it is something that will be sorted I will wait.  It is more work to change websites.

**Comment by Robinmcgvr** [comment]
Matteo has recovered some of the data , but we are still missing 11-14 th
I am just waiting for him to confirm that he has recovered as much as he could. The website is not allowing me to see data prior to the 14th any more

**Comment by Robinmcgvr** [comment]
Would we be able to get Branko or Jelena to manually schedule the missing bits (once we have confirmation that they can't be recovered) using the elmundo.es?
That way you don't have to mess about with separate loading source for those few days>

**Comment by Lynne12** [comment]
I am loading 8th - 10th now and will wait for Matteo's response before working out the gap filling.

**Comment by Lynne12** [comment]
@Robinmcgvr is there an update from Matteo on this?

**Comment by Robinmcgvr** [comment]
15-22 march still missing and not going to be possible to recover

**Comment by Lynne12** [comment]
@Robinmcgvr 15-22 March has never been missing.  The date range missing was 11-14 March, but this now appears on Kablam and has been loaded.
