### ISSUE TITLE
Switzerland - blue.ch

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#136]
@Robinmcgvr TELECLUB is missing 31st March - 4 April 2022

**Comment by Robinmcgvr** [comment]
@LYNNE
Hi It seems the channel has ceased, none of our sources are carrying it any more.
i can;t find any information about the channel ceasing or rebranding at this point.
We may replace it with one of the other Blue channels , but for the moment we have no teleclub (TBZ/Blue Prime/Teleclub Prime)

**Comment by Lynne12** [comment]
@Robinmcgvr is there any further update on whether this will be replaced?

**Comment by Robinmcgvr** [comment]
@Lynne12 No not at this point

**Comment by Lynne12** [comment]
Will close this then and a new issue can be raised if we add a replacement channel.
