### ISSUE TITLE
South Afirca - guide.dstv.com

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#137]
We lost data for South African site guide.dstv.com for 12/04 - 21/04 
It's back now, but there is a gap for that period

**Comment by GoodallE** [comment]
On 2022-04-22 17:06, Robinmcgvr wrote:
> We lost data for South African site guide.dstv.com for 12/04 - 21/04
> It's back now, but there is a gap for that period
OK Robin great thanks for letting me know hopefully we will be able to 
use another source or establish a pattern with the eps.

Emma
