### ISSUE TITLE
Croatia-rtl.hr

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#138]
@Robinmcgvr  Data missing 1st & 2nd May

**Comment by Robinmcgvr** [comment]
Thanks Lynne, this was reported to Matteo last week
We are actually missing all data post 1st may - the format of the tv guide on the site has changed.
I will see if Matteo is still able to work with this.

**Comment by Robinmcgvr** [comment]
If we can't fix this we can use the data from tvprofil.com
I will see what Matteo can do.
It looks though from the site that we won't be able to back date this data.

**Comment by Robinmcgvr** [comment]
Matteo reckons he will be able to get this one going again, will confirm once I see some new data
BUT we will not be able to recover the lost data

**Comment by Lynne12** [comment]
@Robinmcgvr data starts again from 9th May, so missing date range is 1-8 May.

**Comment by Lynne12** [comment]
I have asked Richard to set up tvprofil.com, so that I can load the gap in the data for the two channels.

**Comment by Lynne12** [comment]
1-8 May loaded from tvprofil.com

**Comment by Lynne12** [comment]
@Robinmcgvr 31 October is missing

**Comment by Robinmcgvr** [comment]
reported to Matteo

**Comment by Robinmcgvr** [comment]
I have saved pdfs of data for channels RTL, Nova, HTV1 and HTV2 for 01/11 & 02/11/2022 - in case Matteo is unable to recover.
I am unable to get data for 31/10 , so not sure if Matteo will be able to.
But fingers crossed

**Comment by Lynne12** [comment]
@Robinmcgvr data missing for 11th January 2024.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ok thanks , there is nothing to suggest a problem in the kapow folder, ie the days are there and the file sizes are not significantly smaller - so we'll have to see what's gone on here
I can't see your message about the 9-15 Jan in here now, was there a problem with those dates or not?

**Comment by Lynne12** [comment]
It's just 11th missing.  You can ignore the previous, deleted, message.

**Comment by Robinmcgvr** [comment]
OK we have partial data for the 11th but not enough to populate the whole day
It is still available on the site, so I'll see if we can get that recovered too

**Comment by Robinmcgvr** [comment]
That data for the 11th has been recovered so the whole day is covered now

**Comment by Lynne12** [comment]
11th loaded.
