### ISSUE TITLE
Czech - tvprogram.nova.cz

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#14]
@Robinmcgvr Nova Cinema is missing from the above website from 25th April 2020.  Is Matteo aware of this?

**Comment by Robinmcgvr** [comment]
@Lynne12

No,  because I was not aware of it either

**Comment by Robinmcgvr** [comment]
@Lynne12

It's back from the 28th so missing a few days, I will try and keep an eye on this one for a bit to check it carries on behaving

**Comment by Robinmcgvr** [comment]
@Lynne12

Matteo has been informed and I have asked if he can recover those three days, plus sort out a back up source.  Will let you know - but give it a few days

**Comment by Robinmcgvr** [comment]
@Lynne12
I am going to manually schedule those 3 days into studio for now.
I am doing this way because I have no other way currently to save the data available from new site I have found idnes.cz 
We may end up having to manually schedule that chunk anyway if the data can't be recovered from the usual loading source.

**Comment by Robinmcgvr** [comment]
Hmm the data on the idnes.cz and tvprogramnova.cz sites has time differences - sometimes 2 hours sometimes 1!
God knows why. But that could cause some issues when/if you do load data again - let me know when you are ready to load data for that week, and which source you are going to use - I know you don't know yet - but I will make adjustments to the data to enable the loading to work (ie delete or adjust times on a few airings)

**Comment by Lynne12** [comment]
Again this is available to go back on, so no need to manually schedule at this stage and then have to mess about deleting the data.  We can allow Matteo to advise on data recovery or new site:-

http://tvprogram.centrum.cz/den/2020/4/29/

**Comment by Robinmcgvr** [comment]
Ah cool , I missed that the channels were available on there. That is good

**Comment by Robinmcgvr** [comment]
site tvprogram.nova.cz data is now recovered

**Comment by Robinmcgvr** [comment]
We don't necessarily have to revert to using the site, whatever is easiest option for you.

**Comment by Lynne12** [comment]
@Robinmcgvr thanks and will stick with the site, as it is already set up.
