### ISSUE TITLE
m-net.dstv.com

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#144]
there is a problem with site m-net.dstv.com currently.
There has been no download since 23/05 - there is only data from 27/05 onwards still available on the site.
Can you confirm which channel(s) you use this data for?
I can't get anything earlier than today to print, but there is data back to 27th available on the site.
I don't know if you want to take note of the ep details given while we see if Matteo is able to recover the data.

**Comment by GoodallE** [comment]
On 2022-05-30 11:27, Robinmcgvr wrote:
> there is a problem with site m-net.dstv.com currently.
> There has been no download since 23/05 - there is only data from 27/05
> onwards still available on the site.
> Can you confirm which channel(s) you use this data for?
> I can't get anything earlier than today to print, but there is data
> back to 27th available on the site.
> I don't know if you want to take note of the ep details given while we
> see if Matteo is able to recover the data.
Hi Robin

We use this for :

MNET

ME

But I think we will be ok and can source the missing dates from other 
sites. I will take note of these though just incase.

Thanks

Emma

**Comment by GoodallE** [comment]
On 2022-05-30 11:27, Robinmcgvr wrote:
> there is a problem with site m-net.dstv.com currently.
> There has been no download since 23/05 - there is only data from 27/05
> onwards still available on the site.
> Can you confirm which channel(s) you use this data for?
> I can't get anything earlier than today to print, but there is data
> back to 27th available on the site.
> I don't know if you want to take note of the ep details given while we
> see if Matteo is able to recover the data.
Just checked other sites and we have nothing for those channels, i'm 
sure i can work around this though. But would be good to get it back if 
we can.

Thanks

Emma

**Comment by Robinmcgvr** [comment]
Hi,
Matteo has managed to fix and restore data from this site now. ME and MNET aren't showing in kablam yet as this was only downloaded yesterday, but it is there in Kapow.
Hopefully it will be accessible in Kablam in next day or two.

**Comment by GoodallE** [comment]
On 2022-06-01 10:21, Robinmcgvr wrote:
> Hi,
> Matteo has managed to fix and restore data from this site now. ME and
> MNET aren't showing in kablam yet as this was only downloaded
> yesterday, but it is there in Kapow.
> Hopefully it will be accessible in Kablam in next day or two.
That's fantastic! thank you ;)
