### ISSUE TITLE
foxtv.it

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#152]
We are unable to access data from site foxtv.it any more
If you know of another source for the data that we don't currently download, please let me know

**Comment by GoodallE** [comment]
On 2022-07-07 11:07, Robinmcgvr wrote:
> We are unable to access data from site foxtv.it any more
> If you know of another source for the data that we don't currently
> download, please let me know
We were downloading it from sky.it on the +1 channel but that looks like 
it had stopped on the 30/6 all other sites don't seem to download it 
either. I don't have another source but when I get a chance I will see 
if I can find one.

**Comment by Robinmcgvr** [comment]
hmm maybe the channel has ceased as has happened with some of the other Fox channels.
I will have a look

**Comment by Robinmcgvr** [comment]
Yes channel ceased 30/06/2022

**Comment by Lynne12** [comment]
> Yes channel ceased 30/06/2022

@JonathanETS are you aware of this?  I can't assign Brenda in this issue for some reason.

**Comment by Robinmcgvr** [comment]
that's because she is not part of this group

**Comment by JonathanETS** [comment]
Ok that's fine. Channel **Fox** ceased broadcasting...   so we process it through to June 30th and that's it.  I've posted on ETS Issues.  Thanks.
