### ISSUE TITLE
Czech - axn.cz

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#154]
@Robinmcgvr 19th July is missing.

**Comment by Robinmcgvr** [comment]
Sorry, we'll have to use the data from centrum.cz to fill that gap.

**Comment by Lynne12** [comment]
@Robinmcgvr there is nothing on centrum.cz for 19th either.

**Comment by Robinmcgvr** [comment]
Ok then we'll have to refer to the tvepg.eu site
https://tvepg.eu/en/czechia/channel/axn/2022-07-19
It will  have to be done manually unfortunately.
I will save a pdf of the page now, in case it's not still available next week to print

**Comment by Robinmcgvr** [comment]
yes you can access the webpage online

**Comment by Lynne12** [comment]
19th July manually scheduled.
