### ISSUE TITLE
Ireland - tvguide.co.uk

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#16]
RTE1 and RTE2 are missing the following dates:-

10 - 30 April 2020 - RTE1
11 April - 1 May 2020 - RTE2

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ok is that all that you have found missing from the site?
We have at least two back up sites for data for those channels .
It may not be worth the recovery work.

**Comment by Lynne12** [comment]
@Robinmcgvr that is all I have found on the current week of loading (28th April - 4 May)

**Comment by Robinmcgvr** [comment]
@Lynne12 
Those channels are there when I look at the kapow data for 28/04 to 01/05

**Comment by Robinmcgvr** [comment]
@Lynne12 
Maybe an issue with the formulation of the channel names? ie gaelic style.

**Comment by Lynne12** [comment]
@Robinmcgvr this is actually a bigger date range and I have amended the post above.
There is a problem with the channel names on Kablam and I will refer this to Richard.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ok great - if it continues to be a problem there is entertainment.ie or rte.ie
