### ISSUE TITLE
Switzerland - 3plus.tv

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#160]
@Robinmcgvr data is missing for 17th August 2022.

**Comment by Robinmcgvr** [comment]
Thanks, the day is not actually missing , but most of the data is. Seems to be still available on the site, so hopefully Matteo can fix this day - if  not we do have back up data on upctv.ch

**Comment by Robinmcgvr** [comment]
Data is now recovered

**Comment by Lynne12** [comment]
Data loaded.
