### ISSUE TITLE
Romania - Pro X

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#165]
@Robinmcgvr Pro X changed it's name, back in April, to Pro Arena.  This does not now appear on any of our Kablam sources.  Would you be able to get Matteo to add this please, to any of the applicable sources.  Many thanks.

**Comment by Robinmcgvr** [comment]
I'll see what we can do, find which sites carry it etc, and pass the info on to Matteo

**Comment by Robinmcgvr** [comment]
we do have the channel in the tvepg.eu.ro downloads, no synopsis info though.

**Comment by Robinmcgvr** [comment]
We have recovered the data for this channel back as far as August at this point, Matteo says he can go further so I may as well get to him to go as far as he can to help with the checking

**Comment by Robinmcgvr** [comment]
Matteo has managed to update data for Pro Arena back to Feb 2021 - this may be more useful for checkers than inputters - but it's helpful
