### ISSUE TITLE
Sweden-viasat.se

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#168]
@Robinmcgvr data missing for 15th & 16th November.

**Comment by Robinmcgvr** [comment]
OK I have asked Matteo to recover and have downloaded some back up pdfs as a back up from source tv.nu
I noticed that we are no longer getting these channels from tv.nu so have also asked if we can reinstate them for back up source purposes

**Comment by Robinmcgvr** [comment]
Data has been recovered

**Comment by Lynne12** [comment]
Missing data loaded
