### ISSUE TITLE
Portugal: nos.pt

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#169]
@Robinmcgvr Kablam is missing 28th November.

**Comment by Robinmcgvr** [comment]
OK thanks for letting me know, this wouldn't have been picked up til friday as the data loads in the evening of the day. 
I will see if we can get it recovered

**Comment by Robinmcgvr** [comment]
It's not been recovered yet, not sure we will get it now - I did alert matteo last week

**Comment by Robinmcgvr** [comment]
30th nov has been recovered

**Comment by Robinmcgvr** [comment]
No we aren't going to be able to recover this we will have to manually schedule the missing day

**Comment by Lynne12** [comment]
@Robinmcgvr I have loaded this date from the the alternate websites set up for Portugal.
