### ISSUE TITLE
VTM Kzoom changed to VTM KIDS

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#17]
@Lynne12 
The channel VTM Kzoom has rebranded as VTM Kids , unfortunately our downloads have not been picking up the new version of the channel.

I have asked Matteo if he can recover back data to March 1st for this one .
So that means that the March Belgium man scheduling is not actually completed.
I hadn't realised this before, just thought it hadn't shown any relevant films.
Argh!

**Comment by Robinmcgvr** [comment]
That also means that April Belg, man sched is only prepped for Vijf and Plug-RTL

**Comment by Lynne12** [comment]
@Robinmcgvr thanks for the info.  You may wish to inform Jackie and Emma, as I had notified them that March scheduling was complete.

**Comment by Robinmcgvr** [comment]
ok done, although i think that it is a Paramount only channel
