### ISSUE TITLE
Romania - Pro Gold - program24.ro

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#170]
@Robinmcgvr the above channel changed it's name in April to http://programetv.program24.ro/post/acasa-gold-hd/data-14.11.2022.html

Could you please ask Matteo to do the necessary amendments, so that this downloads on Kablam, please, 

program24.ro

**Comment by Robinmcgvr** [comment]
Have requested Matteo adds to program24.ro and cinemagia.ro

**Comment by Robinmcgvr** [comment]
This channel has now been added
