### ISSUE TITLE
Sweden-viasat.se

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#171]
@Robinmcgvr Kablam is missing 3-31 December 2022 & 1-2 January 2023

**Comment by Robinmcgvr** [comment]
Thanks, this was reported to Matteo on monday

**Comment by Robinmcgvr** [comment]
This site seems to have changed to ' https://www.allente.se/tv-guide/' now - Matteo is working to set this one up
We won't be able to recover the missing data 
We'll have to see what the data looks like once it starts downloading
Pain in the neck that this one has changed again!

**Comment by Robinmcgvr** [comment]
It looks like if the data downloads ok we should use this for Cmore channels and viasat film premiere as the site does cover the early hours that tv-tabla.se misses.
We may though need to use that one to fill the gaps as best we can for the lost days
Actually a combo of this and tv.nu (manual I guess) will cover those early hours airings

**Comment by Robinmcgvr** [comment]
Matteo has set up a new directory/site for sweden 'allent.se' I have asked Richard to add this to Kablam
He has downloaded data to 01/12/2022

**Comment by Lynne12** [comment]
> Matteo has set up a new directory/site for sweden 'allent.se' I have asked Richard to add this to Kablam He has downloaded data to 01/12/2022

@Robinmcgvr can you let me know once this is all set up please.  It is still not on Kablam.  Once it is I will arrange for Richard to change the loading source for these channels.

**Comment by Robinmcgvr** [comment]
Request was logged with Richard , so I am waiting on him to add this to Kablam, I have just given him another nudge now

**Comment by Lynne12** [comment]
@Robinmcgvr I have requested Richard to change the online scheduling loading source to allente.se

**Comment by Lynne12** [comment]
@Robinmcgvr the change has been made to allente.se and I am loading the missing date range.
