### ISSUE TITLE
France - tv-programme.telecablesat.fr

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#173]
@Robinmcgvr 23-26 December is missing.

**Comment by Robinmcgvr** [comment]
have you informed matteo?

**Comment by Lynne12** [comment]
@Robinmcgvr no, I haven't.  I am also on holiday and was just catching up with some bits.

**Comment by Robinmcgvr** [comment]
Data has been recovered for 23-26th
