### ISSUE TITLE
Serbia-telegraf.rs

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#176]
@Robinmcgvr Missing 26 December 2022 - 2 January 2023 - PINK PREMIUM & PINK FAMILY
Missing 28th December 2022 - 2 January 2023 - PINK

**Comment by Robinmcgvr** [comment]
Thanks, all were reported to Matteo yesterday

**Comment by Lynne12** [comment]
@Robinmcgvr Missing 3-9 January 2023

**Comment by Robinmcgvr** [comment]
This site no longer carries a TV guide , so it is now useless to us unfortunately

**Comment by Lynne12** [comment]
@Robinmcgvr we will need a new source for the following channels:-
PINK, PINK FAMILY, PINK PREMIUM

I can use tv.aladin.info for Pink Family, as we already use this website.  

Pink Premium and Pink are only found on tvprofil.com and mojtv.net.rs, both of which we stopped using because the websites were problematic.

**Comment by Robinmcgvr** [comment]
We will have to try using one of those sources for now, I don't think there are any other serbian sites to try at this point

**Comment by Robinmcgvr** [comment]
tvprofil looks like the better option data wise

**Comment by Robinmcgvr** [comment]
I see you have preferred to go with mojtv - I do think from analysis that tvprofil data is closer to what we were getting from telegraf

**Comment by Lynne12** [comment]
If you look I amended the website to tv profil, after I saw your message.

**Comment by Robinmcgvr** [comment]
ah ok, lag in messages

**Comment by Lynne12** [comment]
Pink Family & Pink Premium loaded 26 December 2022 - 9 January 2023.
RTV Pink loaded 28 December 2022 - 9 January 2023.
