### ISSUE TITLE
Portugal: nos.pt & guia-tv.pt

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#179]
@Robinmcgvr 6th February is missing.

**Comment by Robinmcgvr** [comment]
The guide seems to have disappeared from this site as of 29/03
I'll try and find a new one as we lost a couple of the other portugese sites too

**Comment by Lynne12** [comment]
Missing dates, 27th & 30th March onwards.  The 28th and 29th are available.

**Comment by Lynne12** [comment]
Missing 1-10 April 2023

**Comment by Robinmcgvr** [comment]
There is still no guide on this site, I have asked Matteo to set up some new ones, so am waiting on that.

**Comment by Robinmcgvr** [comment]
Latest news on this is not so good, Matteo is being blocked from recovering back data , he has set up tvepg.eu going forwards.
The other sites I found are no good for downloading from , so I am looking for some more.

**Comment by Robinmcgvr** [comment]
I am going to try and do this by accessing the data myself and entering it manually to plug the gaps. This will be skimmed for only the most relevant titles
Ah one of my new sites does work - it is **guia-tv.pt** and data starts from 11/04 so that's a bit better. I'll add this to the list of sites we want adding to kablam, then you could try this one out for loading .
(There is a blank ten days even on tvepg.eu from 06/04/2023 - 13/04 (inc), so even with the new site we are going to be missing 6-10 April unfortunately, but it is a bit better than having three weeks missing at least)

**Comment by Robinmcgvr** [comment]
Data from 30/03 - 05/04 entered for TVi and Sic - there is no data on any source from 6-10th

**Comment by Lynne12** [comment]
> I am going to try and do this by accessing the data myself and entering it manually to plug the gaps. This will be skimmed for only the most relevant titles Ah one of my new sites does work - it is **guia-tv.pt** and data starts from 11/04 so that's a bit better. I'll add this to the list of sites we want adding to kablam, then you could try this one out for loading . (There is a blank ten days even on tvepg.eu from 06/04/2023 - 13/04 (inc), so even with the new site we are going to be missing 6-10 April unfortunately, but it is a bit better than having three weeks missing at least)

@Robinmcgvr if you could let me know when the website is added to Kablam.  I am currently loading data from 11/4/2023, so will need to catch up with Portugal once it is ready and I instruct Richard to set up the new loading source.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Richard says he has added the site to Kablam now, data should be available from Monday (back to the start date)

**Comment by Lynne12** [comment]
@Robinmcgvr I have asked Richard to add the website for data loading.  Please note that there is not a full days data on Kablam for either channel until 12th April.  5th-11th only contains part days.

**Comment by Lynne12** [comment]
@Robinmcgvr the guia-tv.pt site is not great.  Branko has picked up that there is a lot of overlapping times during the days.  He started fixing them, but this is not ideal going forwards, would be very time consuming and defeat the object of online scheduling.  Perhaps you can take a look to see if there is an alternative and I will stop using this for now for loading.

A couple of examples below.

TV4P | 01/05/23 | 13:00 | 14:00 | 60 |   | CONTA-ME:T2 EP.131

TV4P | 01/05/23 | 13:58 | 15:55 | 117 |   | TVI JORNAL
L13194899 | - | - | - | - | TVI JORNAL

****

TV4P | 01/05/23 | 22:30 | 23:45 | 75 |   | FESTA E FESTA:T6 EP.611

TV4P | 01/05/23 | 22:40 | 02:00 | 200 |   | O TRIANGULO - GALA
L13194919 | - | - | - | - | O TRIANGULO - GALA

TV4P | 01/05/23 | 23:45 |   | 0 |   | O TRIANGULO - EXTRA
L13194916 | - | - | - | - | O TRIANGULO - EXTRA

**Comment by Lynne12** [comment]
@Robinmcgvr I can also see that there are long durations and it appears lots of timeslot gaps in the days too.  SICP also has the overlaps, like TV4P.

SICP | 06/04/23 | 23:45 | 19:40 | **1195** |   | FLOR SEM TEMPO:T1 EP.56
L13405536 | - | - | - | - | FLOR SEM TEMPO:T1 EP.56

**Comment by Robinmcgvr** [comment]
So far most of the overlaps i can see are for local programming , so not so much of an issue,
I will have another look for a source but I think I have exhausted most options, maybe tvepg could work but there will be no details, but we have the others for reference.

**Comment by Robinmcgvr** [comment]
I've asked Matteo to start downloading tvepg data back to  01/05/2023
I'll let you know when it's ready - it will be at least a week I imagine

**Comment by Robinmcgvr** [comment]
I've just discovered that we are already pulling data for tvepg.pt but bizarrely it is in the netherlands kapow & kablam folders
This might mean you can load it already.
I have though asked Matteo if it can be moved into the Portugal folder

**Comment by Lynne12** [comment]
@Robinmcgvr, Richard may be able to move the folder?  I can't tag him on this repository though.  Let me know the outcome, as I don't want to get the loader set up whilst it is in the wrong folder, or I will have to get that changed again after it moves.

**Comment by Lynne12** [comment]
@Robinmcgvr let me know the outcome, as I don't want to get the loader set up whilst it is in the wrong folder, or I will have to get that changed again after it moves.

**Comment by Robinmcgvr** [comment]
@Lynne12 
There is somethjng weird going on now, maybe it's a transitional phase, Matteo says he has moved the data and in kablam I can see data back to 18/05/2023 now - BUT this is not showing in the Portugal Kapow folder (where it should be) 
So I don't know what is going on.

**Comment by Lynne12** [comment]
@Robinmcgvr I can see the data, in Kablam, from 18 May.  Are we going to get the date range 1-17 May?

**Comment by Robinmcgvr** [comment]
@Lynne12 
We have it, it is just in the wrong place still at the moment - I am waiting for it to get fixed

**Comment by Lynne12** [comment]
I have requested Richard to set up the new loading source for these two channels.

**Comment by Robinmcgvr** [comment]
Two things to report on this. 
1) the data is still only showing back to 18/05
(issues with moving data not yet resolved)
2) Having taken a look at the data that is in kablam we are still getting some overlaps! (grr) they tend to be a doubled up airing with the first the correct duration , so the second could be ignored or deleted. I don't know why it is doing this as the data in tvrepg.eu site is not.
Neither is the data in the Kapow files! so this would seem to be a kablam problem.
I will discuss with Matteo and also Richard to see if we can get to the bottom of what is going on and sort it out So the saga continues I am afraid

**Comment by Robinmcgvr** [comment]
n.b. I am adding Richard and Matteo as collaborators on this repository BUT could I ask please that only I refer things to them? Or it only happens after consultation with myself?
As I am usually discussing the issues with Matteo and they rarely need further action, but in the odd case , like this one, it would be useful for them to be able to see the discussion trail or details on the issue.
They don't need to be tagged in on every issue we have with kapow data

**Comment by Lynne12** [comment]
tvepg.eu.pt is now set up as the loading source, but I will hold off loading until the issues are sorted.  For reference, SICP & TV4P are loaded up to and including 30th April 2023.

**Comment by Lynne12** [comment]
@Robinmcgvr is there an update on this, please?  We have no data loaded for this channels past 30th April.

**Comment by Robinmcgvr** [comment]
Not really no I am afraid, I chased it up with Matteo last week. He says it needs Richard to sort it out.
I have requested his assistance, again. Hopefully he can sort it.

**Comment by Robinmcgvr** [comment]
In the short term you could load the data from netherlands folder (mad I know) - this may keep the overlaps though.
It depends how urgently the data is required. For BMI WGA it's not much of an issue yet, I don;t know about the other clients

**Comment by Lynne12** [comment]
I don't want to be setting up another loading source, having not long set this up, if it is not guaranteed that the data will be okay.  This also needs Richard to be involved, if we do have to set up.  I guess @JonathanETS can advise how long we want to wait?

**Comment by JonathanETS** [comment]
@Lynne12 @Robinmcgvr @RichardFord 

At the moment the four Portuguese channels are under contract with WGA and Entertainment One. They're advertised as standard channels and thus will be covered for other ad hoc jobs here and there, so it's useful to have them in sync with other countries but right now this is not critical.  

Both WGA and E-One are quarterly clients with a lag of several months, so there is time to sort this out before setting up new data sources.  Obviously the sooner it's sorted the better.

Q2 2023 for EOne has to be delivered latest by end of September and WGA ideally with a four month lag but no later than 5 months (so end of October / end of November).  This means the data needs to have been input a few weeks beforehand in order for checks and other processes to occur (not least episodes for WGA).   (NB. the goal is always to reduce turnarounds where possible - all clients want a quicker turnaround.)

**Comment by RichardFord** [comment]
> Not really no I am afraid, I chased it up with Matteo last week. He says it needs Richard to sort it out.
> I have requested his assistance, again. Hopefully he can sort it.

Is there a request I have missed?

**Comment by Robinmcgvr** [comment]
@RichardFord 
We alerted you to this issue some weeks back - email 23/06 gave some background to the issue
Raised in support 03/07

**Comment by RichardFord** [comment]
That missing data going back to 10th April is now there

**Comment by Robinmcgvr** [comment]
Hurrary - thanks! 
The only weird thing is that in kapow files , this data still shows as being in the Netherlands folder - so I don't know why that is. But so long as the data is loadable and accessible in Kablam - I am happy

**Comment by Robinmcgvr** [comment]
Just to confirm we are talking about the tvepg.eu (pt) data ?
Which is now available back to May in Kablam - 
Whether the overlap issue persists is the other thing we need to assess

**Comment by RichardFord** [comment]
yes

**Comment by Robinmcgvr** [comment]
And yes it does, there are still overlaps on this data when viewed from Kablam

**Comment by Robinmcgvr** [comment]
Also I am unable to get this data via catkapow - I just end up with empty files
Whereas I can get from Kablam ? !

**Comment by RichardFord** [comment]
screenshot the options you are using

**Comment by Robinmcgvr** [comment]
![image](https://github.com/Robinmcgvr/Kapow-Data/assets/29253360/72684133-8bb7-4cf7-9d15-6dcce9aa323d)

**Comment by Robinmcgvr** [comment]
![image](https://github.com/Robinmcgvr/Kapow-Data/assets/29253360/c423daa1-f995-4d9e-93d1-2edcc9b6c4ed)

**Comment by Robinmcgvr** [comment]
![image](https://github.com/Robinmcgvr/Kapow-Data/assets/29253360/c32d15fb-17cf-4e24-b6d3-50eb62e85303)

**Comment by RichardFord** [comment]
Why are you using tvepg.eu? The email says tvepg.eu.pt

**Comment by Robinmcgvr** [comment]
![image](https://github.com/Robinmcgvr/Kapow-Data/assets/29253360/90198c03-0d53-402b-bcda-6e970020b3d6)

**Comment by Robinmcgvr** [comment]
All options have been tried see the window in right hand page

**Comment by Robinmcgvr** [comment]
latest shows the data sitting in the folder tvepg.eu.pt in netherlands
Trouble with this site is that the data comes from the site tvepg.eu

**Comment by RichardFord** [comment]
I have no idea what I'm meant to be fixing now, sorry. I need clearer instructions.

**Comment by Robinmcgvr** [comment]
We were unable to load the data - data we did have had overlaps
Somehow folders have been mixed up 
Now even though we can load the data - which is good - obv. it still looks like it is in the wrong place - however if we can load what we want to load then maybe that is good enough and I can just ignore where the data looks like it is sitting when I look in Kapow/Kablam.
I was trying to concatenate it via cat akpow so I could compare with the data being generated via csv from Kablam as before I find evidence that the 'straight' or 'raw' data in kapow was good vs. the data in Kablam having overlaps 
Overlapping data was what set this whole issue off in the first place

**Comment by RichardFord** [comment]
This data is now fixed as best it can be.

There are still a few overlaps in the early morning. This is because (as an example) the scraped file for 2023-05-17 also contains some records for the 18th. 

We need Matteo to stop scraping the early hours to stop this from occurring.

**Comment by RichardFord** [comment]
Heres an example which is the 9th of July. It contains records for the 10th. 

![image](https://github.com/Robinmcgvr/Kapow-Data/assets/1451549/43ac3103-f2df-4e30-b2bf-619ec40e8315)

**Comment by JonathanETS** [comment]
@Robinmcgvr   

To be clear...  the early hours transmissions (after midnight before 6am) are being picked up twice...  once on the actual day and also on the day before (as part of the broadcast day).  These txs have slightly different times between the two days.  So Matteo needs to try and restrict the Kapow downloads to only scrape the actual date for each date and the not the post midnight records.

**E.g. 1. Kapow file for May 21st includes records for 22nd...**
![image](https://github.com/Robinmcgvr/Kapow-Data/assets/23121277/a482bc66-81a4-4886-9e4f-54835b223331)

**E.g. 2. Kapow file for May 22nd has same records but they have different times...**
![image](https://github.com/Robinmcgvr/Kapow-Data/assets/23121277/6c1a3881-41be-41b0-ad60-cc19bf9c10d2)

**Comment by Robinmcgvr** [comment]
Yay thanks guys ! I will forward this to Matteo now

**Comment by Lynne12** [comment]
@Robinmcgvr once I load the data for this everything from 1st May, up until Matteo makes the changes will need to be manually amended, as advised by Richard.

**Comment by Robinmcgvr** [comment]
Hmm maybe best before you give Branko the go ahead to process that I go in and fix the data in maintain .
Probably better if I do this one week at a time - then give the go ahead for it to be processed

**Comment by Robinmcgvr** [comment]
It should only be early hours airings affected anyway - so shouldn't be a lot of work

**Comment by Lynne12** [comment]
Yes, that's fine.  I will let you know when it is loaded.  If you can keep me updated on when Matteo makes the fix, so we can work out where we need to stop making the amendments, please.  I will be loading 1st May - 3 July as the initial date range, to bring it in line with other online scheduling loading dates and then weekly thereafter.

**Comment by JonathanETS** [comment]
Might be easier to delete the rows from the kapow files before loading.  You just need to go into each file and delete the records with the next date ??

**Comment by Robinmcgvr** [comment]
I don;t think I can edit kapow files

**Comment by Robinmcgvr** [comment]
I think if we let Lynne load the first month - so May 2023, then I can take a look at how it presents in studio

**Comment by Lynne12** [comment]
> Might be easier to delete the rows from the kapow files before loading. You just need to go into each file and delete the records with the next date ??

Richard had said that nothing could be done now that the are scraped, but you may want to check this with him.

**Comment by JonathanETS** [comment]
hmm maybe not so easy...  cos they are csv files...  you'd probably have to open in notebook to preserve fomatting...  ok ignore that.

**Comment by Robinmcgvr** [comment]
So Lynne, just load the one month please for now.
I can then take a look and see what work is actually involved

**Comment by JonathanETS** [comment]
...and I guess they are already ingested into Kablam...  so a double ignore that.

**Comment by RichardFord** [comment]
Its not possible. The data is pulled out of Kablam which has already been loaded. You will have to delete it from Studio when processing, sorry..

**Comment by Robinmcgvr** [comment]
Yeah that's what we're going to do

**Comment by Lynne12** [comment]
Both channels are loaded from 1st May - 3 July, to bring it in line with the other channels/countries.  I am on holiday from Wednesday, so not available to load it a bit at a time. It would also cause more work to do it that way. It is loaded ready for whenever you are ready to make the amendments, for each month.  I will not instruct Branko to work on May data until after that months amendments are made.  There will be further dates to be loaded and amended, going forwards, until Matteo confirms the changes are made.

**Comment by Robinmcgvr** [comment]
@MatteoETS 
HI Matteo, having compared the data we are downloading from site tvepg.eu with what we ended up with in kablam. I think it's not quite as simple as Richard suggested above. The site, as you probably know. displays two days at a time but in fact truncates the end of the second day , then one sees the whole day when one sets the date to the next day .
so e.g. call up 05/05/2023 and you can see 06/05/2023 as well BUT this ends at 21:50 . when I select the date 06/05/2023 the data now goes up to 23:25 - so I think this may be another factor in what is happening with this data. Not every day behaves like this, it depends on the duration of the final airing listed.
We found another site the other day that I asked you to try downloading meo.pt - so I am hoping that this site if it is suitable and may be a better option altogether (fingers crossed)
Therefore could you do a test download of this new site before you put too much work in to, as Richard suggested, to tvepg.eu data?

**Comment by MatteoETS** [comment]
Hi all,
I changed the tvepg.eu and tvepg.eu.pt robots so that they scrape only the actual date, skipping the transmissions starting after midnight.
Changes will be effective from tomorrow's run.

I also set up a robot for meo.pt, which looks good and fast. 
I am not getting the tranmission details at the moment, but I will if needed.

**Comment by JonathanETS** [comment]
> Hi all, I changed the tvepg.eu and tvepg.eu.pt robots so that they scrape only the actual date, skipping the transmissions starting after midnight. Changes will be effective from tomorrow's run.
> 
> I also set up a robot for meo.pt, which looks good and fast. I am not getting the tranmission details at the moment, but I will if needed.

Thanks Matteo!

**Comment by Lynne12** [comment]
@Robinmcgvr Branko will soon be starting on the June scheduling.  Please let me know when you have amended the two channels, ready for him to work on.  Many thanks.

**Comment by Robinmcgvr** [comment]
May Portugal data checked and corrected 
Will let you know when June ready to work on

**Comment by Robinmcgvr** [comment]
June Portugal OK to work on now

**Comment by Lynne12** [comment]
@Robinmcgvr data is currently loaded up to 17th July.  I can see that the problems still persist with this date range.  Please let me know once these are corrected and in addition can you let me know the date from which the data starts to be okay.

**Comment by Robinmcgvr** [comment]
@Lynne12 
It looks like the data is OK from the 17th onwards.
I will fix the loaded data before July starts being worked on
