### ISSUE TITLE
Canada citytv.com

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#18]
@goodallE

Data from site citytv.com Canada, is not currently downloading .
It is listed as an OPR site , is this one you still use?
Looks doubtful we will get this guide back due to the change in format of the tv guide.
Could you let me know if the site is still used for OPR work?

**Comment by GoodallE** [comment]
On 2020-05-18 11:40, Robinmcgvr wrote:
> @goodallE
> 
> Data from site citytv.com Canada, is not currently downloading .
> It is listed as an OPR site , is this one you still use?
> Looks doubtful we will get this guide back due to the change in format
> of the tv guide.
> Could you let me know if the site is still used for OPR work?
Hi Robin,

Yes it is one we use as a secondary source, if the primary source is 
unavaliable or has no information.

Thanks

Emma

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?

**Comment by Robinmcgvr** [comment]
I suppose so yes. It wasn't actually for your attention

**Comment by Lynne12** [comment]
@Robinmcgvr I am aware of that but it is an issue from May and Emma had answered your question.  I am going through issues relating to scheduling and spotted this old one.
