### ISSUE TITLE
Taiwan-dngtw.tw

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#180]
@Robinmcgvr data missing for 1-9 February 2023.  This website is used for Hong Kong SMHD channel

**Comment by Robinmcgvr** [comment]
Ah the channel smithhd has dropped from the downloads here, as the days are all there ( I don't check every channel)
The channel is back from the 10th , I will see if the data can be recovered, but it's doubtful

**Comment by Robinmcgvr** [comment]
Futher to this, we have been missing the early morning data from this channel for several months - I only saw this when checking that the data was working properly today.
Obviously as this wasn't picked up before we won't be able to recover it ... but I have asked Matteo to see if there is anything he can to do fix this going forwards
