### ISSUE TITLE
Missing Kapow data for online scheduling week 7-13 March 2023

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#182]
@Robinmcgvr there are multiple missing dates, various countries, for this week.  Irum has been liasing with Matteo, so hopefully all of these have been covered.  Documenting them here so that I can keep track if any are recovered:-

- [ ] Australia-Albany, Albury, Cairns Missing 8th
- [ ] Austria - tv-media.at Missing 7th & 8th (ORF1&2) 7th,8th,9th (ATV, PULS4, SERVUS TV)
- [ ] Czech-mujtvprogram.cz Missing 7th & 8th
- [ ] New Zealand-tvnz.co.nz Missing 8th
- [ ] Portugal-nos.pt Missing 7th & 8th
- [ ] Serbia-tv.aladin.info Missing 7th & 8th
- [x] Serbia-tvprofil.com Missings 7th,8th, 10th-16th
- [ ] Serbia-extratv.me Missing 7th & 8th

**Comment by Robinmcgvr** [comment]
Australia-Albany, Albury, Cairns Missing 8th - yourtv also missing
 Austria - tv-media.at Missing 7th & 8th - tele.at also missing
 Czech-mujtvprogram.cz Missing 7th & 8th - tvepg.eu site only
 New Zealand-tvnz.co.nz Missing 8th - sky.nz possibly?
 Portugal-nos.pt Missing 7th & 8th - rtp.pr (SICP & TV4 are not on rtp.pt)
 Serbia-tv.aladin.info Missing 7th & 8th
 Serbia-tvprofil.com Missings 7th,8th, 10th-16th -  dates restored, may need to check channels
 Serbia-extratv.me Missing 7th & 8th -

**Comment by Lynne12** [comment]
@Robinmcgvr where is the tvepg.eu website located on Kablam, for the HBO Czech channel?
@Lynne12  Ah i meant the website itself ...ie will have to be manually scheduled from there

**Comment by Lynne12** [comment]
@JonathanETS channels affected by the missing dates:-

AUSTRALIA-GWNP, PR16, NBN3, WINT, QTVT
AUSTRIA-ORF1, ORF2, ATV, PULS4, SERVUS TV
CZECH-HBO
NEW ZEALAND-NZ1&NZ2
PORTUGAL-SICP&TV4P(TVI)
SERBIA -PINK KIDS, PINK FAMILY, PINK 2

**Comment by Robinmcgvr** [comment]
https://tvepg.eu/en/czechia/channel/hbo/2023-03-08

**Comment by Robinmcgvr** [comment]
We may be able to use this site for a fair bit of the missing euro data. If you could please raise the channels and dates required as a separate issue, either I can get it to at some point or we can get someone else to do the required manual scheduling

**Comment by Lynne12** [comment]
> We may be able to use this site for a fair bit of the missing euro data. If you could please raise the channels and dates required as a separate issue, either I can get it to at some point or we can get someone else to do the required manual scheduling

@Robinmcgvr I have raised individual issues on the Manual Scheduling repository.
