### ISSUE TITLE
Ireland-RTE2 - tvguide.co.uk

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#183]
@Robinmcgvr RTE2 appears to stop on Kablam from 28th February onwards.  I am currently loading the week 14-20 March and it is still not available.

**Comment by Robinmcgvr** [comment]
Ok yes I see it's missing too, I'll ask Matteo to recover - the alternative is to load from rte.ie if you want to get data loaded more quickly

**Comment by Lynne12** [comment]
rte.ie used to load 28th February.  Will wait to see if Matteo can recover the source for March data.

**Comment by Lynne12** [comment]
@Robinmcgvr March data has been loaded from rte.ie.  RTE2 is still no available on tvguide.co.uk going forwards into April.

**Comment by Robinmcgvr** [comment]
What I suggest is you use the RTE2 HD from tvguide.co.uk going forwards from 03/04/2023 and I can manually enter the 1 and 2nd using one of the Irish sources. Unless you want to add those two days from rte.ie as well, or keep using that source for the channel.
But I know it's better and easier to not keep switching sources. 
Let me know how you deal with that and I'll raise an issue in the manual scheduling to remind me that those couple of days need entering should that be the case.

**Comment by Lynne12** [comment]
@Robinmcgvr 1st & 2nd April loaded from rte.ie.  3rd loaded from tvguide.co.uk, which had renamed the channel as UK
tvguide.co.uk
RTE2 HD
Will use tvguide.co.uk going forwards.  There is nothing to be manually scheduled.
