### ISSUE TITLE
Ireland-uk tvguide.co.uk

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#185]
@Robinmcgvr the following are missing:-

RTE1 - April 18, 21, 23
RTE2 - April 19, 21-24

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ok I'll ask Matteo to try and recover the data

**Comment by Robinmcgvr** [comment]
@Lynne12 
Mateo has only been able to recover data for the 24th April I am afraid
If it's too much of a pain to load that week from RTE.ie then I can manually schedule these days, although not immediately

**Comment by Lynne12** [comment]
@Robinmcgvr I will load remaining data from rte.ie

**Comment by Lynne12** [comment]
RTE1 missing 29/4 & 1/5
RTE2 missing 25th & 28th April
Loading missing dates from rte.ie
