### ISSUE TITLE
Belgium online scheduling - moustique.be

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#19]
@Robinmcgvr we are missing data for 5-18 May 2020

**Comment by Robinmcgvr** [comment]
yes I am aware and it was reported a while back, it is still missing now, I have not had any feedback on it from Matteo yet.
I will chase him up on it now

**Comment by Robinmcgvr** [comment]
We have BE1 in cinetelerevue.be data should we need it

**Comment by Robinmcgvr** [comment]
@Lynne12 
Moustique.be data is back now, all there for whole of May to date.
let me know if you have any further issues loading this data.
