### ISSUE TITLE
Ireland: tvguide.co.uk

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#190]
@Robinmcgvr the following are missing:-
RTEI 27-31 May
RTE2 5 June

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ok I'll report to Matteo, to see if it can be recovered - also 03/06 only has partial data for RTE One

**Comment by Robinmcgvr** [comment]
(btw I don't need assigning as I created the repository)

**Comment by Lynne12** [comment]
In view of Matteo's response the gaps have been loaded from rte.ie Ireland.

**Comment by Lynne12** [comment]
RTE1 missing 6,7,10,11 June
RTE2 missing 6 June
Will load from rte.ie
