### ISSUE TITLE
New Zealand Online scheduling 27.6.2023-3.7.2023

### ISSUE THREAD

**Issue by JackieColes** [Robinmcgvr/Kapow-Data#196]
@robin missing dates for NZ3 as follows:

26/6/2023
27/6/2023
28/6/2023
29/6/2023

**Comment by Robinmcgvr** [comment]
can you confirm the kablam source please?

**Comment by JackieColes** [comment]
apologies....sky.co.nz

**Comment by Robinmcgvr** [comment]
thanks, hmm seems the data is missing further back than that

**Comment by Robinmcgvr** [comment]
I don't know if we will be able to recover to source sky.co.nz BUT we do have data for the channel on nzcity.co.nz
So we can use that if we need to

**Comment by Robinmcgvr** [comment]
I can see that on the missing days the file size for downloads on sky.co.nz was smaller, so I will keep an eye on this.
I will ask Matteo if it is possible to recover the data

**Comment by Robinmcgvr** [comment]
Matteo is unable to recover this data - so it will need loading from the alternative source nzcity.co.nz

**Comment by Lynne12** [comment]
@JackieColes I have requested Richard to set up this alternate loading source.  ETS-Issues #1626
Once this is done then the missing days can be loaded by pulling the CSV from Kablam.

**Comment by Robinmcgvr** [comment]
n.b. after that week the data is OK - so if the other site is preferable it can be transferred back again

**Comment by Lynne12** [comment]
We will continue loading from the main website the following week.  The alternative loading source will just be for gap filling.

**Comment by Lynne12** [comment]
Missing dates loaded.

**Comment by Robinmcgvr** [comment]
Are you guys aware that there is a 12 hour time discrepancy between data from nzcity and sky.co.nz? 
The timing of the news programmes is the proof of it.
I think we need to either get sky data shifted by 12 hours or switch to loading from nzcity - everything we are producing for this channel has the wrong times

**Comment by Robinmcgvr** [comment]
This came to light when I was trying to fill in some gaps

**Comment by Robinmcgvr** [comment]
This is the only source we have for sky movies premiere , but maybe we should switch Three to nzcity going forwards?

**Comment by Robinmcgvr** [comment]
OK this is all giving me a serious headache now, trying to back track to look at the earlier issues that made us switch sources before and try and make sense of it.
I have asked Matteo if he can fix the 12 hour discrepancy on sky site

**Comment by Robinmcgvr** [comment]
ok we're going to leave the sky.co,nz as it is

**Comment by Robinmcgvr** [comment]
Issue with nzcity is that the last programme of the day doesn't get an end time only the start time repeated/
Have Matteo looking again at whether he can adjust the data from sky.co.nz or get another site I found to work

**Comment by Robinmcgvr** [comment]
n.b. time fix applied to manual entered data for 24/06/2023 to 26/06/2023
Richard will adjust times  by 12 hours from 01/04/2023 to 25/06/2023 inclusive

**Comment by Robinmcgvr** [comment]
This has now been done - may have to make same adjustment to Q3

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed?

**Comment by Robinmcgvr** [comment]
I want to keep this open as a reminder about having to adjust the studio data by 12 hours because we are loading from Sky.co.nz
