### ISSUE TITLE
LOST KAPOW DATA

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#2]
We have lost data from SKY.IT covering 28/11/2019 to 02/12/2019 -this is not recoverable

Hopefully we can find data for the channel TMC2 elsewhere.

**Comment by Lynne12** [comment]
3-9 December is also missing.

**Comment by Robinmcgvr** [comment]
Thanks this is in Matteo's hands and he says he has recovered data, so I am waiting to hear back from him on this

**Comment by Robinmcgvr** [comment]
re. sky.it , although a pain to be missing data for checking and other purposes - we are going to drop channel Italy TMC2 (MTV) from 01/01/2020 , so missing these days of it won't matter.

**Comment by Lynne12** [comment]
@Robinmcgvr can you confirm that Italy TMC2 (MTV) has now been dropped?

**Comment by Robinmcgvr** [comment]
@Lynne12 
Just waiting confirmation from JB but am 80 % sure we are

**Comment by Robinmcgvr** [comment]
@Lynne12 
That is now confirmed

**Comment by Lynne12** [comment]
Thanks Robin
