### ISSUE TITLE
Switzerland srf.ch

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#20]
HI Lynne,

We are missing data for site SRF.ch back to 20th May - it has been reported to Matteo,
I will let you know when it has been fixed

**Comment by Lynne12** [comment]
For reference this applies to:-
Germany - 3SAT & SUDW
Switzerland - SF1 & SF2

**Comment by Robinmcgvr** [comment]
@Lynne12
Data is now back, had a quick look, channels look ok
