### ISSUE TITLE
Online Scheduling 11/7/23-17/7/23

### ISSUE THREAD

**Issue by JackieColes** [Robinmcgvr/Kapow-Data#200]
@Robinmcgvr missing dates for the following countries and channels:

BELGIUM - moustique.be -  channel BE1 missing 17th July 

FRANCE- telelecabsat- channels PPRE, SERIE CLUB and TEVA missing dates 15th and 16th July

NEW ZEALAND - sky.co - NZ3 missing 10th July

**Comment by JackieColes** [comment]
Ignore my message for New Zealand

**Comment by Robinmcgvr** [comment]
Reported to Matteo

**Comment by Robinmcgvr** [comment]
Looks like moustique has reduced the number of channels it covers , now only french language channels and not all of them. It could be  temporary thing, I'll keep an eye on it. For the 16th July for example we only have data for BE1 and no other channels, so something funny has been going on with the site
Cinetelerevue covers BE1- so we might have to switch to that if needs be

re telcabrsat.fr - the way the channelsa re displayed in its guide might have changed as now one has to select another page to get the next group of channels up - I have asked Matteo to see if he can work with this or not
