### ISSUE TITLE
belgium- moustique.be

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#201]
No data post 17/07 - few days beforehand we lost several channels - site has changed its format.
Will have to see what Matteo can do with this

**Comment by Robinmcgvr** [comment]
Still no data for this site

**Comment by Robinmcgvr** [comment]
This site is also blocking us 
Matteo is trying his work around for this one too

**Comment by Lynne12** [comment]
Data is available from 31st July.

**Comment by Robinmcgvr** [comment]
We only have a very few channels being pulled for this site at the moment

**Comment by Robinmcgvr** [comment]
Most are covered by cinetelerevue if there are problems and we may need to use this site to plug the gaps in the July data

**Comment by Lynne12** [comment]
@Robinmcgvr 22-25 November missing.
