### ISSUE TITLE
Portugal-tvepg.eu.pt

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#203]
Data missing 27 July - 7 August 2023

**Comment by Robinmcgvr** [comment]
Yeah bad news on this one , all the tvepg.eu versions are blocking us now !
matteo is seeing what can be done but it's not looking too hopeful
We set up a new portugal source recently meo.pt I am waiting for Richard to add this to Kablam - so the saga of portugal data continues I'm afraid

**Comment by Robinmcgvr** [comment]
meo.pt site is now set up in kablam

**Comment by Lynne12** [comment]
@Robinmcgvr are we changing SIC & TV4 to this source?

**Comment by Robinmcgvr** [comment]
I think it could be a good idea to do so.
There are still overlaps in the early hours data for the July data on the system, ok only one per day now it looks like. But also the meo gives ep info in the title text and even if it is not Branko who does the ep work on this it would make it a bit easier to have this info more readily available.
There could even be an argument for switching all of portugal to this source - but maybe for now just the sic and Tvi - see how it works with the loading and episode matching in atelier

**Comment by Lynne12** [comment]
Gaps loaded from meo.pt and loading source changed to this website.
