### ISSUE TITLE
Spain-movistarplus.es

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#205]
@Robinmcgvr this is the last entry on the website for CAPS Spain

Aug 1, 2023 | 05:50 | 17:50 | movistarplus.es | M+ #0 |   | M+ #0

**Comment by Robinmcgvr** [comment]
@Lynne12 
I have looked into this how and the channel ceased on 31/07 so that would explain it.
It doesn't seem to have changed into anything else

**Comment by Robinmcgvr** [comment]
I've let JB know the channel has ceased now

**Comment by Lynne12** [comment]
@RichardFord can you please remove Spain, movistarplus.es from the weekly downloads for online scheduling, please.

**Comment by RichardFord** [comment]
Done
