### ISSUE TITLE
New Zealand Online Scheduling

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#206]
Could we change the loading source we use for NZ1 etc to tvnz.co.nz instead please?
This is because that site gives episode info (titles/numbers) in the guides which would also be imported with the data.
Could we start doing that with with October data onwards please?
Let me know if there are any issues with that.

**Comment by Lynne12** [comment]
tvnz.co.nz only has TVONE and TV2.  Can you confirm these are the correct channels?

**Comment by Robinmcgvr** [comment]
Yes those are the correct channels

**Comment by Lynne12** [comment]
Data is already loaded up to and including 18th October, so any changes will be after that date.

**Comment by Robinmcgvr** [comment]
OK if that is the earliest date we can do,  if unloading that isn't possible.

**Comment by Lynne12** [comment]
@Robinmcgvr NZ1 and NZ2 loading source changed.  Data loaded from 19th October 2021.

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed, please.
