### ISSUE TITLE
Croatia - novatv.hr

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#21]
@Robinmcgvr 23 & 24 May missing.  Can you let me know when tvprofil.com is recovered (checked Kablam today and these dates are not there).

**Comment by Robinmcgvr** [comment]
@Lynne12 
I will let you know when the May data has been fully recovered , shouldn't be too long.

**Comment by Robinmcgvr** [comment]
Are you intending to fill those gaps via manually scheduling those 2 days only?
Would seem the best idea , then we don't have to mess about with changing loading sources again.

**Comment by Lynne12** [comment]
I'm going to keep any eye on these new sites, going forwards.  If they start to cause issues I will switch back to the one.

**Comment by Robinmcgvr** [comment]
fair dos.

**Comment by Robinmcgvr** [comment]
May tvprofil data seems to be back for all of May - I haven't checked the actual data yet though

**Comment by Lynne12** [comment]
@Robinmcgvr I have checked the data for the missing dates I need and all looks fine, so will load the gaps from tvprofil.com
