### ISSUE TITLE
Serbia-Pink Premium

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#225]
@Robinmcgvr Pink Premium stops on tvprofil.com on 5th January.  I am filling the gap from 6-8 January from tv.aladin.info.  If there is nothing on tvprofil.com next week I will switch the loading website permanently.

**Comment by Robinmcgvr** [comment]
recovery of this site is under way, it will take til the end of this week to fully recover acc. matteo
It has restarted its standard download yesterday and he will carry on recovering the missing data .

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?
