### ISSUE TITLE
Austria tv-media.at

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#227]
We are missing some channels from this site for 08/01/2024 - inc all the Orf channels.
It has been reported to Matteo, the data is still available on the site, so hopefully we will be able to recover the data

**Comment by Lynne12** [comment]
@Robinmcgvr there are also various dates, for various channels missing from the week 9-15 January 2024.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ok thanks, again there is nothing in the kapow folder to show that there is missing data for these dates, ie no reduction in file size apart from for the 8th, so I will look at the actual files

**Comment by Robinmcgvr** [comment]
ATV & ATV2 - 12/01 Missing
ORF1, 2 & 3 - 08/01 and 12/01 Missing
Servus - 08/01 & 12/01 Missing
Puls 4 - 08/01 & 12/01 Missing

We might be able to recover the 12th as it's still available on the site
08/01 was previously reported , but was not able to be recovered

**Comment by Robinmcgvr** [comment]
12th has been recovered

**Comment by Lynne12** [comment]
@Robinmcgvr 12th loaded. 8th is available on tele.at.  You may wish to take a look at the data and let me know if you want me to load this?

**Comment by Robinmcgvr** [comment]
@Lynne12 
This slipped my mind and given that you will now be away for two weeks I will manually fill these gaps
