### ISSUE TITLE
Mexico - mi.tv

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#23]
@Robinmcgvr the above website is missing 22nd June 2020

**Comment by Robinmcgvr** [comment]
@Lynne 
Ah these sneaked past me, although I had checked them on monday, these are sites that usually are one day behind, so on Monday's check nothing looked wrong - I will ask Matteo to try and recover.

**Comment by Lynne12** [comment]
Data loaded
