### ISSUE TITLE
New Zealand channel Three missing 02/04/2024

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#238]
We didn;t get this channel for the 02/04 and although reported quickly it has not been recovered, so we are going to have a gap for that day unfortunately.

I have just found another site that carries all the NZ channels we want and have asked Matteo to set it up , fingers crossed!

**Comment by Robinmcgvr** [comment]
@Lynne12 
New site for NZ which covers  NZ1 , 2 and Three set up in kablam from 10/05/2024 onwards
= freeviewnz.tv

**Comment by Robinmcgvr** [comment]
I think it could be worth considering switching Three loading to this new site based on the amount of gaps in the Q1 data at the point of loading, (data is there in Kablam now - relates back to issues we were having , but we didn;t have this many problems logged, it's a bit like the RTE that always needs gap filling , but worse as it's all out of sync timewise) I'll take a look at the May and June data once I have finished the work on Q1 .

**Comment by Robinmcgvr** [comment]
This would get rid of the 12 hour time lag on the data too, I know you have already loaded June but it would be great if you could delete what you;ve loaded and use the new site/source please so we have better data going forwards
So if you can, please remove june, reload from new site from **02/06/2024**  (this will allow me to adjust for the time discrepancy on the 31/05 old source data)
(Back to 15/05 would be really fab ., so we can use this new data sooner ... in which case reload from 16/05)

**Comment by Lynne12** [comment]
@RichardFord can you please unload the online scheduling data for **New Zealand, CHANNEL 3 (NZ3), from 1 June - 1 July 2024**.

**Comment by Lynne12** [comment]
> This would get rid of the 12 hour time lag on the data too, I know you have already loaded June but it would be great if you could delete what you;ve loaded and use the new site/source please so we have better data going forwards So if you can, please remove june, reload from new site from **02/06/2024** (this will allow me to adjust for the time discrepancy on the 31/05 old source data) (Back to 15/05 would be really fab ., so we can use this new data sooner ... in which case reload from 16/05)

@Robinmcgvr May data has already been processed, so I will leave this.

**Comment by Robinmcgvr** [comment]
Ok , thanks for giving the go ahead to reload June

**Comment by Lynne12** [comment]
Once this is done I will reload 2 June onwards from the freeviewnz.tv website.

**Comment by RichardFord** [comment]
> @RichardFord can you please unload the online scheduling data for **New Zealand, CHANNEL 3 (NZ3), from 1 June - 1 July 2024**.

Its been removed

**Comment by Lynne12** [comment]
NZ3 loaded 2 June-1 July from freeviewnz.tv, which is now set up to be the weekly loading website.
