### ISSUE TITLE
Czech Republic - hbo.cz

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#24]
@Robinmcgvr the above website is missing 21st June 2020

**Comment by Robinmcgvr** [comment]
Data is still missing for all 3 european hbo sites, cz, hu & pl

**Comment by Robinmcgvr** [comment]
This data is lost from the hbo sites you will need to use the back up sources for the day either by loading that week from them , or getting Branko/Pavle to manually schedule using them.

**Comment by Robinmcgvr** [comment]
czech = mujtvprogram.cz
Hungary = tvmustra
Poland is not listed as online scheduled - is that correct?

**Comment by Lynne12** [comment]
21st June is not missing for Hungary and yes it is correct that we don't do online scheduling for Poland.

**Comment by Lynne12** [comment]
21st June, HBO Czech, loaded from centrum.cz
