### ISSUE TITLE
Switzerland-srf.ch

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#240]
@Robinmcgvr srf.ch is missing 28th April.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Yes this is part of a bigger problem we have had over the weekend, affecting various sites, we are still working on it- it's nothing like as bad as last occasion but about 25 sites have been affected

**Comment by Robinmcgvr** [comment]
This data has now been recovered

**Comment by Lynne12** [comment]
Data loaded.
