### ISSUE TITLE
Ireland - rte.ie

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#249]
@Robinmcgvr the above website is missing 8th July.

**Comment by Robinmcgvr** [comment]
Ok thanks for letting me know, last data check was Monday so that date wouldn;t have been seen until next check on Friday

**Comment by Robinmcgvr** [comment]
How often do you check your loading sites? Maybe you could help out with some of the kapow checking while I am off, at least your sites on the friday  02/08 ? I should be able to do the check the previous friday ...

**Comment by Lynne12** [comment]
@Robinmcgvr I load the online scheduling Wednesday/Thursday weekly.  I only know there is data missing once I run the weekly file download.  I can report any on those days, if that helps?

**Comment by Robinmcgvr** [comment]
Yes thanks,  that would be great, while I am off

**Comment by Lynne12** [comment]
I always report missing dates, weekly, for the online scheduling sites, in any event, unless you notify me first.  I would log them on an individual issue.  Is that sufficient or will you need something more?

**Comment by Robinmcgvr** [comment]
Your usual method is fine, thank you!

**Comment by Robinmcgvr** [comment]
Matteo has recovered the data for 08/07
