### ISSUE TITLE
KAPOW FAILURE 1ST JULY ONWARDS

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#25]
@Lynne12 

Unfortunately all sites have failed to download from 1st July onwards.
Matteo has been informed, but it will probably take a while to sort out.
I have sent him a list of the loading sites so he knows that these are a priority.
I will check in with him on Monday when I was planning to do Monday's Kapow check anyway

**Comment by Lynne12** [comment]
Oh dear, that's not good news.  Will wait on any updates.  I am due to start loading July scheduling data on Wednesday 8th.

**Comment by Robinmcgvr** [comment]
@Lynne12 
I think it's unlikely there will be enough data recovered to do any loading this week.
Matteo is working on it , it's a memory issue apparently.
But you never know it may be quicker process than I think, maybe take a look to see what dates data is available to in kapow or kablam before you try to load any.
Jonathan is on the case about it too so he may be able to update you on the situation.

**Comment by Lynne12** [comment]
I will hold off, although I will load 30th June today so that June is ready to work on in its entirety (this date would have been included in the early July loading).  I have logged the countries that Matteo has listed as unrecoverable on the Issues Chart, for your perusal and comment.

**Comment by Lynne12** [comment]
@Robinmcgvr can you update me on channels/countries recovered once you hear from Matteo, please.

**Comment by Robinmcgvr** [comment]
@Lynne12 
I am in midst of putting together a chart of what has been recovered to the 1st and what hasn't, when I am finished I will send it over to you.
Won't be much longer

**Comment by Lynne12** [comment]
@Robinmcgvr thank you.  Did you mean 1st-4th, as this is the missing date range?

**Comment by Robinmcgvr** [comment]
yes

**Comment by Robinmcgvr** [comment]
@Lynne12 
Updates oN Kapow 
CH (SWITZERLAND)
TELE.CH does cover channels RSI 1 & 2, plus RTS 1 & 2 (BUT THIS IS STILL MISSING 3RD JULY)
SRF.CH covers channel Puls 8 & SRF1 & 2

SE (SWEDEN)
VIASAT.SE - (VIASAT FILM PREMIERE) it is actually the 2nd rather than the 1st that has missing data.

RO (ROMANIA)
Antena 1 - I have recovered data for 1-4 July from programetv.program14.ro -
only in either pdf or printed out - but at least we can work with this.

PO (PORTUGAL)
SIC.SAPO.PT & TVSAPO.PT - sic and TVI covered by these sites - again we may need to manually schedule ti fill the gaps, to avoid having to keep changing loading sources.

I shall update the list further as I find more options for online or manual scheduling data.

**Comment by Robinmcgvr** [comment]
@Lynne12 
More updates

DE (Germany)
SRF.CH - also covers BR, WDR & NDR

CZ (CZech Rep.)
IDNES.CZ -covers NOVA ACTION, NOVA 2
