### ISSUE TITLE
Belgium-moustique.be

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#250]
@Robinmcgvr the above website is missing 15th July.

**Comment by Robinmcgvr** [comment]
15th is recovered - 16th now missing - asked Matteo to check this Robot

**Comment by Lynne12** [comment]
15th July loaded.

**Comment by Lynne12** [comment]
@Robinmcgvr 26, 27 & 29 July are missing.

**Comment by Robinmcgvr** [comment]
@Lynne12  Those July dates above have been recovered

**Comment by Lynne12** [comment]
@Robinmcgvr 26 August is missing.

**Comment by Robinmcgvr** [comment]
Thanks this was logged with Matteo last week, he has not as yet recovered the data,
We have the data for BE1 on either telenet.tv, guidetv.be or programme-tv.be -we may have to manually schedule it from one of those sources

**Comment by Lynne12** [comment]
@Robinmcgvr 19-21 September is missing.

Thanks - this wasn't visible on monday as downloads from this site are generally 2 days behind

**Comment by Lynne12** [comment]
@Robinmcgvr should we be thinking about changing the loading source for this channel?

**Comment by Robinmcgvr** [comment]
@Lynne12 
Hmm good question, I will ask Matteo to investigate what the issues are here, and inform him of the latest missing chunks, these weren't apparent on monday as there is a 2 day lag with data from this source .
I will also look at the quality of the data we have from our other sources to see if any might be preferable.

**Comment by Robinmcgvr** [comment]
telenet.tv would be the best choice if we were to switch as this is the only one other than moustique that gives the correct durations on end of day transmissions. 
I'll get back to you on this once I have discussed with Matteo

**Comment by Robinmcgvr** [comment]
Matteo, is doing some work on the moustique data to hopefully stop the gaps we have been getting lately.
He thinks this is a fault in the Kapow software itself. There is work in progress to start a new server for our Kapow data .
(This possibly dates back to the software update we had few months back that caused a system failure.)
But fingers crossed we should have the moustique data back behaving soon, maybe hold off loading until the end of this week to give this time to take effect?

**Comment by Lynne12** [comment]
@Robinmcgvr there are no missing days showing on this weeks file (24-30 September).

**Comment by Lynne12** [comment]
@Robinmcgvr 17-21 October missing.

**Comment by Robinmcgvr** [comment]
@Lynne12 
This was reported on Monday to Matteo

**Comment by Robinmcgvr** [comment]
Although 17-21 recovered we are now missing 26/10 - 31/10

**Comment by Robinmcgvr** [comment]
Actually this data has been recovered but it;s currently in a different folder - should get moved over soon

**Comment by Lynne12** [comment]
17-21 October loaded.

**Comment by Lynne12** [comment]
> Although 17-21 recovered we are now missing 26/10 - 31/10

@Robinmcgvr please note the missing date range is now 26th October - 2 November.

**Comment by Lynne12** [comment]
@Robinmcgvr any update on this missing data?

**Comment by Robinmcgvr** [comment]
yep this has all been recovered, however from there onwards the files have gone tiny again

**Comment by Lynne12** [comment]
@Robinmcgvr **26 October - 2 November** is not available in Kablam.
The following missing dates have been loaded, 26, 27, 29 July, 26 August.

**Comment by Lynne12** [comment]
Missing July and August dates have been translated.

**Comment by Robinmcgvr** [comment]
@Lynne12 
I am investigating this now, why data not showing in kablam - I'll get back to you when have an answer
it is there in kapow , I have opened files to check

**Comment by Lynne12** [comment]
@Robinmcgvr 26 October - 2 November loaded from moustique.be.bck

**Comment by Lynne12** [comment]
@Robinmcgvr 22-30 November is missing.

**Comment by Robinmcgvr** [comment]
@Lynne12 
yes we have missing data again on this source, so I think we should switch to alternative source telenet.tv

**Comment by Lynne12** [comment]
Loading source changed to telenet.tv (please note a 2 hour time difference from moustique.be) and 22-30 November loaded.
