### ISSUE TITLE
Australia-ourguide.com.au

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#253]
@Robinmcgvr Albury is missing 3 August.  This relates to channels PR16 & NBN3.

**Comment by Robinmcgvr** [comment]
I have been able to check the NBN data via yourtv.com / Newcastle in kapow and there was only Olympics coverage, news or Aussie football, so we can leave that day out
Prime now seems to exactly shadow 7 so the data from Sydney 7 can be used to plug the gaps here.
We have also had a problem with ontvtonigh which is another back up source, but Matteo is working on this.
We won;t be able to recover the Albury data now.
I've saved a file and will pin a note that this day's data needs to be manually scheduled

**Comment by Lynne12** [comment]
@Robinmcgvr Albury is missing 6th August.

**Comment by Robinmcgvr** [comment]
This was reported to Matteo - but not been recovered

**Comment by Robinmcgvr** [comment]
03/08 & 06/08
Data added via Seven Aus Sydney and NBN Checked via yourtv Newcastle
