### ISSUE TITLE
Serbia-tv.aladin.info

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#258]
@Robinmcgvr data missing 11-13 September, for PINK KIDS.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Thanks, the dates were reported to Matteo last week, he doesn't seem to have been able to recover the data, it is available on tvprofil.com

**Comment by Lynne12** [comment]
Missing dates loaded from tvprofil.com
