### ISSUE TITLE
Romania - program24.ro

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#26]
@Robinmcgvr the above website is missing 5&6 July 2020

**Comment by Robinmcgvr** [comment]
well we will probably just have to deal with that

**Comment by Robinmcgvr** [comment]
@Lynne 
Actually I already recovered data for this if it's A1 you're after, but only in either print out or pdf form

**Comment by Lynne12** [comment]
@Robinmcgvr it covers the following channels:-

PRIMA
PROTV
TVR1
TVR2
KANALD
AXN

**Comment by Robinmcgvr** [comment]
@Lynne12 
Most of those are avaialble via other kapow/kablam sources namely:
primatv.ro
Pro.tv
Tvr.ro
axn.ro

I will see if I can get KanalD

**Comment by Robinmcgvr** [comment]
@Lynne12 
Matteo has managed to recover those days for us.
