### ISSUE TITLE
Switzerland-blue.ch

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#272]
@Robinmcgvr 4th November is missing.

**Comment by Lynne12** [comment]
@Robinmcgvr is there any news on this, please?

**Comment by Robinmcgvr** [comment]
@Lynne12 
No the data is lost

**Comment by Robinmcgvr** [comment]
tvsearch.ch has data for Blue Action and Blue Stars

**Comment by Lynne12** [comment]
4th November loaded, from tvsearch.ch.  Please note a 1 hour time difference between this website and blue.ch
