### ISSUE TITLE
Ireland-rte.ie: October

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#273]
@Robinmcgvr the following channels are missing 24-28 & 30 October, TG4, TV3 (Virgin Media One)

**Comment by Robinmcgvr** [comment]
Yes this was logged with Matteo at the time, but the data was not recovered, we will have to load via entertainment.ie I'm afraid

**Comment by Lynne12** [comment]
Data loaded from entertainment.ie
