### ISSUE TITLE
Poland - stopklatka.pl

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#275]
This site now has a robot detection on the site, I have asked Matteo if it's possible to get around this, but it's not looking too hopeful.
Last data we have is 09/12

**Comment by Robinmcgvr** [comment]
Matteo has been able to recover the data from this site - yay!

**Comment by GoodallE** [comment]
On 2024-12-30 16:58, Robinmcgvr wrote:
> Matteo has been able to recover the data from this site - yay!
That's great! Thank you!
