### ISSUE TITLE
Mexico - AMC

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#28]
@Robinmcgvr mi.tv is missing 5 July 2020, as part of the missing date range on Kablam. There appears to be no alternate website for this.

**Comment by Robinmcgvr** [comment]
the whole day is actually there in the kapow data, so I am not sure what's happened there - I can email it to you to give to the inputters to manually fill in the gaps.

**Comment by Lynne12** [comment]
@Robinmcgvr the data you attached to your email is for 5th May 2020.

**Comment by Robinmcgvr** [comment]
oops! Sorry about that , was working on May data for something else at the time.
So we are in fact missing Mi.tv for 5th July - I will see if Matteo is able to pick this up.

**Comment by Lynne12** [comment]
@Robinmcgvr any news on this day, please?

**Comment by Robinmcgvr** [comment]
I have just checked and the data is now there.

**Comment by Lynne12** [comment]
Great, thanks!
