### ISSUE TITLE
Australia - ourguide.com.au

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#29]
@Robinmcgvr the following are missing 1-5 July 2020, from the missing period of Kablam downloads:-

ALBANY-GWNP

ALBURY-PR16 & NBS3

CAIRNS-WINT & QTVT

Please advise if you have alternate websites for these channels.

**Comment by Robinmcgvr** [comment]
The only alternative source I know for these is 'yourtv' but the same days are probably missing from there too.
So again we will just have to have a gap in this data.

**Comment by Lynne12** [comment]
@Robinmcgvr all regions are missing 29th July 2020

**Comment by Robinmcgvr** [comment]
@Lynne12 
That day seems to be available for all regions on yourtv, are you able to load it from there? I guess it may mean having to do the the whole week , not sure if there are any time differences between those two data sources, but we should be able to work around it.

**Comment by Lynne12** [comment]
@Robinmcgvr I cannot see all the above listed channels on that Website.  If you know they are called different names then please advise of this?

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ah yes for some reason the regions we download from yourtv do not show up in kablam even though this is how they download in kapow which is a bit weird - we do pull GWN7 which is another name for gwn and the data that kablam generates does match the Albany GWN   - so this one is OK . - 29th July manually scheduled.
I will go through the remaining channels and let you know their status. -

**Comment by Robinmcgvr** [comment]
Prime =Prime 7 in yourtv kablam - data matches up - 29th July manually scheduled.
NBN3 = NBN - again data matches to yourtv Newcastle - 29th July manually scheduled
WIN should be OK too, but QTVT needs a little bit more digging ... I'll get back to you on that one in a bit
WIN-29th July manually scheduled

**Comment by Robinmcgvr** [comment]
@Lynne12 
i can't get QTVT 
But these are ok
Prime =Prime 7 in yourtv kablam - data matches up - 29th July manually scheduled
NBN3 = NBN - again data matches to yourtv Newcastle - 29th July manually scheduled
WIN should be OK too - 29th July manually scheduled

**Comment by Lynne12** [comment]
@Robinmcgvr I have looked to pull this data and only 5th July is available on Kablam.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ah yes, I think I was focusing on the 29th July data there , yes we are lacking 1-4 July - we will just have to live with that gap sadly.

**Comment by Lynne12** [comment]
@Robinmcgvr 29th July manually scheduled, with the exception of QTVT.
