### ISSUE TITLE
Australia foxtel.com.au

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#3]
We still have some gaps in the data for foxtel.com , luckily foxclassics.com is ok.
We can use data from that site for scheduling and may be worth switching to this source permanently.

**Comment by Robinmcgvr** [comment]
data is missing from 9-25 november , 27 nov to 2 december and 4th to 10th december

**Comment by Robinmcgvr** [comment]
n.b. data for new fox channels can also be found in yourtv.com.au (under sydney fox in kapow, but channels listed in kablam)

**Comment by Lynne12** [comment]
November data has already been scheduled, filling gaps from Foxclassics.com
