### ISSUE TITLE
Portugal data 4-10 February 

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#30]
@Lynne12 
@JonathanETS 
I have just found that there is a week of missing data for channels SIC and Tvi Portugal covering 4-10th February.
There is no log for this.
Having investigated further I can see that nos.pt seems to have the data, so I am not sure what heppened there.
But the good news is that we do have the data, both from nos.pt and sic.sapo.pt and tvi.iol.pt - so it can be manually added.
So that is what I shall do now unless, Lynne we could load the week ?
It is thanks to Gerard's checking that I was alerted to look at the data as he spotted that some series which one would expect to have seen data for in this week , were missing.

**Comment by Lynne12** [comment]
@Robinmcgvr I've loaded the data, if you wish to process it.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Thanks I will do that now - I  have checked the rest of the quarter and that does seem to be the only significant missing chunk.
I guess there must have just been an error in the loading system during that time.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Just spotted something else a bit weird about this data - for tvi - it has not loaded the first programme on the 4th feb that starts at 00.30 (first dates)- I presume this is not normal - could this be a clue as to why the data didn't load before?
Everything else looks OK , so I will just add in that transmission manually.

**Comment by Lynne12** [comment]
@Robinmcgvr I am unsure as to why it didn't load.  I usually get a message, on the loader if things have failed.  The back up to this would be the inputter advising me that there was no data there, but that can't have happened in this instance.

**Comment by Robinmcgvr** [comment]
This was the period where we had both been away , so that could explain why it slipped through the net. 
Anyway it's sorted now and hasn't had any adverse effect on client data - so all good.
