### ISSUE TITLE
Sweden: tv4:se

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#31]
@Robinmcgvr the above website missing 2 July 2020, from the missing period of Kablam downloads, for the ETS channel TV1000 (Viasat Film Premiere)

**Comment by Robinmcgvr** [comment]
@Lynne12 
The data does seem available from tv.nu website, so i will ask Matte if he is able to recover that.
However if you want to get that week processed for just the one channel for the one day it could be added in manually via the following link https://www.tv.nu/kanal/viasat-film-premiere/2020-07-02

How is the rest of the Swedish stuff you load? Is that all ok for that period?

**Comment by Robinmcgvr** [comment]
n.b. that channel viasat film premiere is not currently being downloaded from tv.nu , so it will take a little longer to sort that out potentially - as he may have to do extra work to incorporate that into our downloads.

**Comment by Robinmcgvr** [comment]
tv4.se will not allow us to go back to that date - hence why tv.nu seems ony option

**Comment by Lynne12** [comment]
@Robinmcgvr I will wait on Matteo to recover from tv.nu, as this is the only issue with Sweden.  We are not working on this country yet, but I am just getting ready for when we do.

**Comment by Robinmcgvr** [comment]
OK I have asked Matteo if he can reinstate the channel to tv.nu and recover the missing data .
I will let you know when , if he manages it

**Comment by Robinmcgvr** [comment]
@Lynne12 
Channel viasat film premiere has now been added to tv.nu data and should cover whole of July (he is working on the August now)
