### ISSUE TITLE
Romania: a1.ro

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#32]
@Robinmcgvr the above website missing 1-4 July 2020, from the missing period of Kablam downloads, for the ETS channel ANT 1

**Comment by Robinmcgvr** [comment]
@Lynne12 
If Matteo had been able to restore the site it would have already been done so I will look to see if there are any live sites that can give us that data - otherwise we will just have to log it in the issues chart as being missing.

**Comment by Robinmcgvr** [comment]
@Lynne12 
I have emailed Matteo about this one and asked him to add it to the program24.ro channels, not sure why it wasn't being included in that data anyway.

**Comment by Robinmcgvr** [comment]
@Lynne12 
This data for the required dates is now available from program24.ro 
However only these dates have had Antena 1 added - does that work for you ? Can you load only 4 days?
The channel is now being included in the daily downloads from the site , but only from around the 12th of August

**Comment by Lynne12** [comment]
@Robinmcgvr 4 days loaded to cover the missing ANT1 dates.
