### ISSUE TITLE
New Zealand: vodafone-nz

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#33]
@Robinmcgvr the above website missing 3&4 July 2020, from the missing period of Kablam downloads, for the ETS channel NSKM

**Comment by Robinmcgvr** [comment]
@Lynne12 
I can't get any data for that period I am afraid, no sites that carry the channel allow us to go back - so that is one that will just have to be logged as having those days missing.

**Comment by Lynne12** [comment]
Logged on Issues Chart
