### ISSUE TITLE
France - 	tv-programme.telecablesat.fr

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#34]
@Robinmcgvr the above website is missing data for 6th - 10th August.

**Comment by Lynne12** [comment]
@Robinmcgvr have you had a chance to look at this?

**Comment by Robinmcgvr** [comment]
@Lynne12 
yes I looked at this yesterday and there are still some problems with the data - a couple of days didn't get their full compliment of channels. I have alerted Matteo to this.
Data for 6-12 Aug looks alright from file size but then the 13th and 15th are small again - you are probably clear to attempt loading up to and including the 12 th.

**Comment by Lynne12** [comment]
@Robinmcgvr I will hang fire until it is all there, as we are only just starting July scheduling.  It is easier to load as a whole week, than have days missing.

**Comment by Lynne12** [comment]
@Robinmcgvr do we have an update on this missing data?

**Comment by Lynne12** [comment]
@Robinmcgvr I have double checked this and we are missing data from early hours of 6th to early hours of 11th.  The remainder of 11th is there and the rest of the month.

**Comment by Lynne12** [comment]
@Robinmcgvr having looked it appears that a lot of the missing dates are now available.  I will check this fully on my return and load the gaps.

**Comment by Lynne12** [comment]
Gaps loaded
