### ISSUE TITLE
Czech online scheduling

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#36]
@Robinmcgvr the following are missing:-

axn.cz 1-4 July 2020
AXN channel 

hbo.cz 1-4 July 2020
HBO channel

iprima.cz 2 July 2020 idnes.cz has half a day for 2nd July.
PREMIERA
PRIMA COOL
PRIMA LOVE

**Comment by Robinmcgvr** [comment]
@Lynne12 
Are you unable to load these channels from any of our alternative sources?

**Comment by Robinmcgvr** [comment]
e.g. mujtvprogram.cz? that should cover hbo at least

**Comment by Robinmcgvr** [comment]
unfortunately idnes.cz will not go back that far in July which is our alternative source for Prima and most other czech channels - so these will also have to be logged as missing.

**Comment by Lynne12** [comment]
@Robinmcgvr I checked the alternate sources before raising the issue.

**Comment by Lynne12** [comment]
@Robinmcgvr I will add these as missing to the issues chart.

**Comment by Lynne12** [comment]
@Robinmcgvr I have loaded the part day 2nd July 2020 for the three Prima channels.
