### ISSUE TITLE
Switzerland online scheduling - rts.ch

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#39]
@Robinmcgvr the following channels are missing 5 September onwards.

TSIS (RSILA1)

TSI2 (RSILA2)

**Comment by Robinmcgvr** [comment]
@Lynne12 
Sorry didn't see this earlier - will get on to it tomorrow

**Comment by Robinmcgvr** [comment]
@Lynne12 
We have the channels on rsi.ch , so at least we are not missing data - but I will alert Matteo that rts.ch has lost channels

**Comment by Robinmcgvr** [comment]
@Lynne12 
rts.ch now fixed
