### ISSUE TITLE
TELECLUB

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#4]
Teleclub.ch site has failed for dates 20-25 dec
Channel is available via tele.ch for manual processing

**Comment by Lynne12** [comment]
Duly noted

**Comment by Lynne12** [comment]
Teleclub.ch is missing for the week 14-20 Jan 2020

**Comment by Robinmcgvr** [comment]
Yes I am aware, it has been reported

**Comment by Robinmcgvr** [comment]
We have the alternative source we set up some months back , we will have to use it

**Comment by Robinmcgvr** [comment]
Tele.ch is your alternative

**Comment by Robinmcgvr** [comment]
A lot of data didn't download yesterday, it looks like the auto -retry has worked and the data is there (pulled today instead) BUT this does mean there could be some potential issues with data for the 23rd Jan - I will try and check these over - to see if all required channels are there

**Comment by Robinmcgvr** [comment]
We are now only missing 13-19 Jan - but will still need to use the alternative source.

**Comment by Lynne12** [comment]
Only 13-16 Jan is now missing.   Will use tele.ch for these 4 days, via manual scheduling.
