### ISSUE TITLE
Switzerland online scheduling - 4plus.tv

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#40]
@Robinmcgvr the above is missing 14th September 2020

**Comment by Robinmcgvr** [comment]
@Lynne12 

Thanks Lynne, got Matteo working on this.
I will let you know when it's back

**Comment by Robinmcgvr** [comment]
@Lynne12 
4plus.tv 14th Sept is now restored

**Comment by Lynne12** [comment]
Data loaded
