### ISSUE TITLE
Hong Kong - epg.i-cable.com

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#41]
@Robinmcgvr the following dates are missing, for the named channel:-

[FAMHK] FOX ACTION MOVIES (HK)
2020-09-24 11:09:45 | --> below threshold >> 14/09/20,
2020-09-24 11:09:45 | --> missing >> 15/09/20, 16/09/20, 17/09/20, 18/09/20, 19/09/20, 20/09/20, 21/09/20, 22/09/20,

**Comment by Robinmcgvr** [comment]
@Lynne12 

I have looked at the website and the channel's listings are missing from the site itself so that would explain, will have to research further , maybe it has ceased or something.

**Comment by Robinmcgvr** [comment]
@Lynne12 

We have the channel on foxmoviesasia.com which we also download so I don't know why it's vanished from the other site.
But at least we have the data there. Fox Family Movies is on there too, as is Fox Movies - but this one comes in without a name so shifting to loading all those Fox channels from foxmoviesasia.com won't work currently .
I will ask Matteo to try and add the channel name for Fox Movies, and we will have to monitor the epg.i-cable.com site and see if the channel returns on there.

**Comment by Lynne12** [comment]
@Robinmcgvr I will load the gaps from foxmoviesasia.com and leave this open for your response from Matteo.

**Comment by Robinmcgvr** [comment]
@Lynne12 
For dates 14-25th Sept inclusive you will have to load 'Fox Movies action' via foxmoviesasia.com , from the 26th September onwards Fox Movies Action is back on epg.i-cable.com. You don't have to switch back to epg.. just letting you know that if you wish to, data is there again for that channel from the 26th Sept
