### ISSUE TITLE
Romania A1.ro

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#42]
@Lynne12 
We are missing data for the above site from 23 September onwards currently, it was reported to Matteo last week but has not yet been fixed. We don't appear to be able to go back on this site, so we will probably need to switch to an alternative loading source for channel Ant 1 for while.

**Comment by Robinmcgvr** [comment]
The site is still not working

**Comment by Lynne12** [comment]
Loaded gap from program24.ro

**Comment by Robinmcgvr** [comment]
@Lynne12 
Great, well done.

**Comment by Lynne12** [comment]
Website is back working from 5th October 2020
