### ISSUE TITLE
switzerland

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#43]
@Lynne12 

We are currently missing data from the following sites:
s1tv.ch - 1,2 oct
4plus.tv - 30/09 - 02/10
6plus.tv 1,2 Oct

Matteo has been informed

**Comment by Robinmcgvr** [comment]
@Lynne12 
4plus & 6plus are now restored.
Still got problems with s1tv,ch

**Comment by Lynne12** [comment]
@Robinmcgvr teleclub.ch is missing from 24th September onwards.  We use this to load channel Teleclub (TCBZ).  I can fill the gap from tele.ch, but are yourself and Matteo aware?

**Comment by Robinmcgvr** [comment]
@Lynne12 
The site is there in kapow, but it seems the channel has dropped out.
I will check the site to see if the channel is still available.

**Comment by Robinmcgvr** [comment]
@Lynne12 
The site is re-directing to https://tv.blue.ch/tv-guide which doesn't seem to cover the Teleclub channels any more
i will see if they are listed under another name.
Are we able to get both the Teleclub sites from the other source?

**Comment by Robinmcgvr** [comment]
ok I have answered that one myself - yes

**Comment by Robinmcgvr** [comment]
@Lynne12 
For your ref. Teleclub Cinema is also available via tvsearch.ch

**Comment by Robinmcgvr** [comment]
@Lynne12 
Ok more on this ...
Teleclub group of channels have rebranded to 'blue' 

What was **Teleclub Star** is now '**blue action'** which is in the teleclub.ch downloads

**Teleclub (cinema)** is now **'blue prime**' 

These are both available in our downlaods from teleclub.ch

So you have options now, you could load both the teleclub channels from the teleclub.ch site or carry on using the sources you were before, ie one from teleclub.ch and one from tele.ch

**Comment by Lynne12** [comment]
@Robinmcgvr I will amend the channel name for Teleclub Cinema and leave Teleclub Star on its current loading site tele.ch

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?
