### ISSUE TITLE
Croatia-tvhr.net

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#44]
@Robinmcgvr the above site is missing the following dates: 13,14, 16-19 October 2020

**Comment by Robinmcgvr** [comment]
@Lynne12 
Thanks Lynne, I am aware and it has been reported to Matteo.
I didn't have the site down as being one we load from. This may be on the latest list you supplied but I have not been able to print that out yet, so it is not readily to hand I am afraid.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Data has been restored now

**Comment by Robinmcgvr** [comment]
@Lynne12 
Is there still a problem?

**Comment by Lynne12** [comment]
@Robinmcgvr no, but you closed the issue before I could take my action to load the data.  This could then slip through the net.  As I opened the issue I would need to close it once it is fully actioned.

**Comment by Lynne12** [comment]
@Robinmcgvr 31 October is missing.

**Comment by Robinmcgvr** [comment]
reported to Matteo

**Comment by Lynne12** [comment]
@Robinmcgvr 10-12 November missing.

**Comment by Robinmcgvr** [comment]
yes this is known about and has been reported, I'll let you know if it gets recovered or not

**Comment by Robinmcgvr** [comment]
@Lynne12 
Matteo has recovered the data

**Comment by Lynne12** [comment]
@Robinmcgvr Kablam only has data up to 10th November.

**Comment by Robinmcgvr** [comment]
it's definitely in kapow, hopefully kablam will update tomorrow as it was downloaded sunday

**Comment by Lynne12** [comment]
@Robinmcgvr there is still no update today.  Not sure if it is relevant but the channel names have changed on Kablam from:- 

ETS Channel- HTV 1 (HTV1) Kablam: Croatia tvhr.net-**hrt1**
 ETS Channel - HTV 2 (HTV2) Kablam: Croatia tvhr.net-**hrt2**
To:
ETS Channel-HTV 1 (HTV1) KABLAM: Croatia tvhr.net **HTV1**
ETS Channel-HTV 2 (HTV2) KABLAM: Croatia tvhr.net **HTV2**

**Comment by Robinmcgvr** [comment]
Hmm in theory that shouldn't make a difference, because whatever is in the kapow file should appear in kablam, I don't have to inform Richard to get new channels into Kablam data, so there must be another problem here .
I'll have to refer to Matteo and Richard

**Comment by Robinmcgvr** [comment]
Sorry I didn't quite understand what you meant when I first read your message. So the data is actually there in kablam just with new channel names, so your problem now is that you are unable to load the data, not that it is missing - so yes that would probably explain why you are having problems and the loading settings will have to be changed I reckon

**Comment by Lynne12** [comment]
No, sorry.  The data is not there in Kablam, but I wasn't sure if Matteo had to make a connection with the Kapow data channel name and the Kablam channel name.
I have loaded 31 October - 9 November, as those dates were there and Richard amended the channel names for the loader.  Only the early hours are there for 10th November and then nothing going forwards, so I have been unable to load any more dates.

**Comment by Robinmcgvr** [comment]
Call up the dates under hrt1 and you will see that the data is there
[tvhr.net_20221110_20221120_hrt1 (1).csv](https://github.com/Robinmcgvr/Kapow-Data/files/10074936/tvhr.net_20221110_20221120_hrt1.1.csv)

**Comment by Robinmcgvr** [comment]
Why it changed to HTV1 for those ten days I do not know - I have raised with Matteo to see if he can do anything about it

**Comment by Robinmcgvr** [comment]
hrt1 is how it presents on the website itself

**Comment by Lynne12** [comment]
Thanks Robin!  What a pain :(  I will get Richard to change them back, now that I have loaded the gap.
