### ISSUE TITLE
Serbia - Pink 2

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#45]
@Robinmcgvr Pink 2 channel is missing from mojtv.net-rs from 14th October onwards.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Thanks Lynne, I will get Matteo on the case.
We do have extratv.me as a back up source if necessary.

**Comment by Lynne12** [comment]
@Robinmcgvr any news on this please?

**Comment by Robinmcgvr** [comment]
@Lynne12 
Matteo was unable to find the channel on the site any more so are you able to use extratv.me?

**Comment by Lynne12** [comment]
@Robinmcgvr website changed, for Pink 2, to extratv.me
