### ISSUE TITLE
Sweden tv4.se

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#46]
@Lynne12 
tv4.se is missing data from 1st November - this has been reported to Matteo

**Comment by Lynne12** [comment]
@Robinmcgvr this is actually missing from 30 October

**Comment by Robinmcgvr** [comment]
@Lynne12 
Update on tv4.se - the site has undergone maintenance and there is currently no guide on the site.
We are monitoring it , but we probably need to use an alternative loading source.

**Comment by Robinmcgvr** [comment]
tv-tabla.se covers the required channels

**Comment by Lynne12** [comment]
I've asked Richard to set up the loader to fill the gaps.  If the issues persist with tv4.se I will make a permanent switch to the replacement website.

**Comment by Lynne12** [comment]
@Robinmcgvr any news on this please? I have just pulled the week 10-16 November and there is still no data.

**Comment by Robinmcgvr** [comment]
@Lynne12 
There is no change, site still has no guide

**Comment by Lynne12** [comment]
I will switch permanently to the tv-tabla.se website, which I have been loading from for the past 3 weeks.

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?

**Comment by Robinmcgvr** [comment]
yep, done
