### ISSUE TITLE
Switzerland - teleclub.ch

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#48]
@Robinmcgvr this website is missing 22nd November.  Are yourself and Matteo aware?

**Comment by Robinmcgvr** [comment]
@Lynne12 
Thanks Lynne, no, that one got past me.
I shall alert Matteo now - good news is that the site will allow us to go back .

**Comment by Robinmcgvr** [comment]
@Lynne12 
Data for this site has been recovered now
