### ISSUE TITLE
3plus.tv switzerland

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#49]
@Lynne12 
Hi Lynne, all data for the plus.tv channels is being covered by 3plus.tv downloads from the 25th November onwards.
All the plus.tv sites are now re-directing to 3plus.tv
This site also covers S1, TV24 TV25 and 6+
So you may wish to use this single source for loading all of the newer Swiss sites going forwards.
You may not wish to change over and that's your call, half of them are manually scheduled anyway.
But the option is there.

**Comment by Lynne12** [comment]
@Robinmcgvr I will take a look at this when I come to load the next week of online data, which covers the period 24-30 November 2020.  I do remember that 3plus.tv caused problems in the past (used to use it for 3+ channel) and we switched to an alternate website.  If the current loading sites for this channel and 4+ continue then I will leave them as is.

**Comment by Lynne12** [comment]
@Robinmcgvr loading website switch made to 3plus.tv for the channel 4+

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?

**Comment by Robinmcgvr** [comment]
Yep. done
