### ISSUE TITLE
23rd Jan missing data

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#5]
re. the Kapow download failure on 23rd Jan ...
This does not look so bad now - we are probably only missing loading data for the following:
Germany - Regional channels (BR, HBB etc) - some could be available via prisma.de 
Belgium - vijf (may yet turn up on of our other sites)
NZ- NKSM (Movies Premieres HD)

Some channels are available via alternative sites and may have to be worked on direct from the website or via printouts I have AB3 france, BE1 and Plug-RTL , Teleclub Cinema & Star

It looks like the sites we use for filling in titles of movie slots for Canada and Latin America should be OK too -  although we could be missing some data - but only for the one day.

Some channels are available via alternative sites and may have to be worked on direct from the website or via printouts

**Comment by Lynne12** [comment]
I have just downloaded the online scheduling files for the week of 21-27 January and the following have 23rd missing:-
Belgium-moustique.be
Germany-tvtv.de (mentioned above)
Romania-a1.ro
Serbia-tvprofil.com

**Comment by Robinmcgvr** [comment]
Yes these will have to be dealt with manually - the belgian channels BE1, plug-RTL are available from programme-tv.net  (via website or I have printouts)
Same for channel AB3
The German channels may be available via prisma downloads, accessible from either kapow or kablam (at least some are)
A1 Romania is available via programtv.ele.ro

**Comment by Robinmcgvr** [comment]
ah yes earlier issue we had with Prisma.de has not been resolved/fixed - so that is a pain, will see if I can find data for those channels elsewhere and get back to you

**Comment by Lynne12** [comment]
All the countries/channels required have been manually scheduled from alternate sources.
