### ISSUE TITLE
Australia Our guide Nov 27

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#50]
@Lynne12 
We had a bit of a problem with data for 27th Nov in australia .
Although most has been restored, it seems we are still missing some data for Albury region, namely NBN - I have asked Matteo if he is able to fully recover data for that day.
But if he can't we may need to use our back up resource 'Yourtv/Newcastle' .

**Comment by Robinmcgvr** [comment]
Prime is also covered by Newcastle data

**Comment by Robinmcgvr** [comment]
@Lynne12 
Albury data cannot be recovered for 27th I am afraid, so we will need to source the NBN and Prime from Yourtv/Newcastle.

**Comment by Lynne12** [comment]
@Robinmcgvr can you confirm that these channels, on Kablam, are NBN and Prime7?  If so the data only starts at 12.15 for both channels.

**Comment by Robinmcgvr** [comment]
@Lynne12 
I have checked the data and it is Prime North we want. Luckily this is also available but via 'ontvtonight' which is also on Kablam.
NBN is on there too - so that in fact is the better back up source for these two channels. (NBN is still there on yourtv/Newcastle)
You don't see those regional suffixes in kablam but that is the way the data is in Kapow , but it was mapped to the correct channels when these sources were set up.

**Comment by Lynne12** [comment]
@Robinmcgvr 1st & 6th December are also missing for these two channels.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Oh dear, yes I can see now that the file is only 17k . It seems the whole ourguide stopped downloading at 03:00 then restarted itself in the evening but missed Albury out on the 2nd run.
We won't be able to recover it so we will have to use the back up source again.
There are plans to create a report that will show the amount of data pulled for each source, which would be helpful for such cases. But when that will happen I don't know.
Now this source has messed up twice I shall ask Matteo to pay it extra attention.

**Comment by Robinmcgvr** [comment]
Matteo is working on fixing the robot for this

**Comment by Lynne12** [comment]
@Robinmcgvr 27th November, 1st & 6th December will be loaded from ontvtonight.com.au

**Comment by Lynne12** [comment]
@Robinmcgvr I noticed 30th November was missing to, so will load this.  You might want to check your dates, to ensure nothing else is missing.

**Comment by Robinmcgvr** [comment]
Thanks Lynne, unfortunately I see that the dates are there or not but not when channels are missing, if the data shows as having been downloaded. 
Matteo is working on fixing the issue with ourguide with Richard , where it is dropping out in the early morning and not restarting properly, so hopefully this particular flaw will be ironed out soon.

**Comment by Robinmcgvr** [comment]
7th to 14th look ok for Prime and NBN on Ourguide/Albury
