### ISSUE TITLE
Sweden viasat.se

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#52]
@Lynne12 
We are missing data from viasat.se from 5th December onwards
Hopefully we can get this recovered, I'll let you know later in the week.

**Comment by Robinmcgvr** [comment]
@Lynne12 
This data is now recovered.
For your ref. channel 'Viasat film premiere' now seems to be called '

V Film Premiere HD

**Comment by Lynne12** [comment]
@Robinmcgvr thank you.  I will load data and you can close this issue now.
