### ISSUE TITLE
Telequebec.tv Canada

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#53]
@Lynne12 
Do you know if the site Telequebec.tv is one that is used for reference by inputters?
The site is playing up and I am not sure if it is actually one we need.

**Comment by Robinmcgvr** [comment]
Ah it seems that the data has been recovered now , it wasn't showing up  in my report.
But it would still be useful to know if it is one that we do need,

**Comment by Lynne12** [comment]
I think the majority use tvpassport.com, but you could also check with Marco for OPR purposes.
