### ISSUE TITLE
lifestyle.com.au

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#54]
Hi Lynne,

This is another site that seems to have ceased.
It looks like we no longer work on this channel. Can you confirm if this is the case please?

**Comment by Lynne12** [comment]
@Robinmcgvr we do still verify this channel, (AULFS) Lifestyle.

**Comment by Robinmcgvr** [comment]
Thanks Lynne,
If anyone is looking for a checking/reference source for the channel Ontvtonight is probably the easiest one to use.
They have probably already figured that out anyway.

**Comment by Lynne12** [comment]
@Robinmcgvr you could maybe add that source to the Best Practice repository, so that everybody can reference it.

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?

**Comment by Robinmcgvr** [comment]
done
