### ISSUE TITLE
maktv.gr

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#56]
Does anyone know what this site is?
It is one we need now for the verifying?
It has just appeared from nowhere , we only have one day's worth of data so far, the 17th Dec - can you let me know if this is one we need?
It seems to cover channel 'Makedonia TV'

**Comment by JonathanETS** [comment]
@Robinmcgvr - Sony are adding Greece to the Verified...  and this is a new channel they want.  It's also been added to the iShow site.  Think I mentioned it on our call.  :-)

**Comment by Robinmcgvr** [comment]
thanks, I knew we were going to be verifiying but wasn't sure about this channel - I will get Matteo onto it as only one day's worth has downloaded

**Comment by Robinmcgvr** [comment]
@Lynne12 
@JonathanETS 
We have lost data for this site again, covering 1-8 Jan , probably the 9th as well, data only available on site today from 10th Jan
I am asking Matteo to prioritise restoring the data as the site doesn't allow us to go back.
I think the site changed the format and the url for the tv guide
