### ISSUE TITLE
Switzerland Tele.ch

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#57]
@Lynne12 
Hi, we are currently missing data for 2nd January onwards from site Tele.ch
Having looked at the site itself it looks like this has become available to subscribers only now.
I will see if Matteo is able to bypass that in any way, but it's looking doubtful.
I think the data we need is covered by Teleclub isn't it?

**Comment by Lynne12** [comment]
@Robinmcgvr there are 3 channels covered by this website:-

TCBS
3PLS
TV24

**Comment by Robinmcgvr** [comment]
@Lynne12 
These are all covered by other download sources I believe.
Think we will have to move to those.

**Comment by Lynne12** [comment]
TCBS loading source changed to teleclub.ch
3PLS loading source changed to 3plus.tv
TV24 loading source changed to 3plus.tv
