### ISSUE TITLE
Thailand mono29.com

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#61]
@Ma-rco 
We have lost data for mono29.com again I am afraid - 3-6 Jan affected, actually 7th looks to have failed again too.
I will ask  Matteo to look at this urgently.

**Comment by Robinmcgvr** [comment]
@Ma-rco 
Hmm not sure the site itself is working anymore - we might need to find a new source - argh

**Comment by Ma-rco** [comment]
> @Ma-rco
> Hmm not sure the site itself is working anymore - we might need to find a new source - argh

Thanks for letting me know!

**Comment by Robinmcgvr** [comment]
@Ma-rco 
@GoodallE 
@Lynne12 
We have definitely lost that site for Mono29, the site just times out every time one tries to access data via various links or even other schedules at this point. If either of you are able to find another source for data for the channel, please let me know.
There could be a small chance that things change, fingers crossed, but it's not looking very good at the moment I am afraid.

**Comment by Robinmcgvr** [comment]
I have found this site which seems to carry the channel, I will see if Matteo can do anything this one.
https://tv.trueid.net/tvguide/all/mono29

**Comment by Robinmcgvr** [comment]
@GoodallE 
@Lynne12 
@Ma-rco 
Matteo is testing a new site we found for Thailand 'tv.trueid.net, - hopefully we can get it to download properly. Covers Mono29 and all the other Thai channels we work on too.
