### ISSUE TITLE
Robot failure 24,25 Jan 2021

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#64]
As you are probably aware we had a major failure over the weekend.
Matteo is working to restore what he can
I am looking for data that I can find where he might not be able to restore it.
We will have to see what we can do, but it is possible we may not be able to recover all data for the period 23-25 January 2021

**Comment by Lynne12** [comment]
@Robinmcgvr I will need a list of all the Online Scheduling sources that are affected please, as per the loading source sheet you have.

**Comment by Robinmcgvr** [comment]
it is all of them, everything

**Comment by Robinmcgvr** [comment]
I am trying to find what I can, when I have done what I can and Mateo has done what he can, we can issue a list of what is still missing and won't be recoverable. At the moment it will data for the 23rd that is most likely to be unrecoverable. Some sites will go back a day but most I have looked at thus far will not go back to the 23rd
This could also affect the 22nd as data from some sites is a day or two behind anyway.

**Comment by Lynne12** [comment]
I will need an update once recovery work has been done and there is a better idea of what is still missing, please.  All as one list, once the recovery work is complete.

**Comment by Robinmcgvr** [comment]
Yep as I said , we will do this later, probably not before end of the week

**Comment by JonathanETS** [comment]
The system is back and robots running....  prioritizing the sites that can't be recovered.

**Comment by Robinmcgvr** [comment]
Matteo  has furnished me with a list of the sites that we will not be able to recover data from. I am going through these to see which cover essential data and what can be captured from the alternative sources we have.
There will unfortunately still be some data missing.
But we are lucky really that this happened over the weekend which meant a smaller amount of data was lost.

**Comment by Robinmcgvr** [comment]
I think it would be a good idea to refrain from attempting to load any data covering the period 23-25 Jan until myself and Matteo have finished the work we are doing on this.
This would save you time and effort reporting and logging missing data, when Matteo and myself are doing the same thing.
I am working on populating the online scheduling list with the info re what's lost and what's not.
I have seen a couple that haven't been restored that could be, as the sites do allow us to go back, so I will alert Matteo to these

**Comment by Lynne12** [comment]
I haven't loaded anything, apart from Netherlands, which was all there.

**Comment by Robinmcgvr** [comment]
@Lynne12 
@GoodallE 
@Ma-rco 
@JonathanETS 
I have sent you all data covering what was lost and what has been recovered etc

**Comment by Lynne12** [comment]
@Robinmcgvr there are anomalies in the list you have emailed me.  Some things marked as missing are recovered, or were never missing in the first place and others that are marked as recovered are not.  I will email you a copy of the list amended where necessary.

**Comment by Robinmcgvr** [comment]
@Lynne12 
The six changes have been noted - are you able to work off the alternative sites suggested?
N.B. Hungary HBO is available from tvmusor.hu
When you have loaded everything let me know what is still outstanding - I presume you will log these gaps in your issues chart?
Otherwise let's set up another page here to list those, so in a central location for easy reference

**Comment by Lynne12** [comment]
I don't think we need any more pages for missing data.  Any remaining can be logged on the January online scheduling page, once I have recovered any that I can from alternate sources.  I already have multiple Github pages that I have to complete and monitor.  It is starting to get confusing.

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed now?
