### ISSUE TITLE
Greece online scheduling - ishow.gr

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#65]
@Robinmcgvr FLMG is missing data for the following November dates:-

5,11,16,17,26

**Comment by Robinmcgvr** [comment]
@Lynne12 
can you confirm which source you were using please?

**Comment by Robinmcgvr** [comment]
and this is channel Nova Cinema 1?

**Comment by Lynne12** [comment]
ishow.gr, the only regular source we use for Greece. It is ETS channel FLMG. Those are the only details I have recorded.

**Comment by Robinmcgvr** [comment]
ok thanks, as this is the kapow repository we do need those details

**Comment by Robinmcgvr** [comment]
@Lynne12 
Upshot is data will not be recoverable at this stage , I have though alerted Matteo to this as it does seem the downloads are somewhat erratic for the source and looks like there will be more days missing for certain channels going forwards too

**Comment by Robinmcgvr** [comment]
Also asked if he can restore channels to pathfinder.gr if possible, so that we have a secondary source going forwards

**Comment by Lynne12** [comment]
@Robinmcgvr FLMG is also missing 19-22 January 2021

**Comment by Robinmcgvr** [comment]
Yes as Matteo informed us, the site does not always display the channel, so in those cases we won't get data - we don't know why
This is also the case with pathfinder, so it must be something to do with the channel

**Comment by Lynne12** [comment]
FLMG is missing data for the following December 2020 dates:-
1,3,7,8,10

**Comment by Robinmcgvr** [comment]
Ok I will see if it is available in any of our other downloads, but as mentioned before sometimes there just aren't any listings for this channel from any source

**Comment by Robinmcgvr** [comment]
@Lynne12 
That december greece data is not recoverable. I have asked Matteo to try setting up new version of the Nova tv guide to see if that helps the situation going forwards

**Comment by Lynne12** [comment]
FLMG is missing data for the following February 2021 dates:-
14-18

**Comment by Robinmcgvr** [comment]
Thanks I have had a bit more of a look into this issue now, the constant loss of data for this channel 'Nova Cinema 1'.
What I have found out is that a bit like Sky Movie channels there is a tendency for the channel to change its name seasonally or themed in some way. This would explain why it disappears from all sources simultaneously.
Some good news and not necessarily explained by what I said above... is that we do have data from a newly revived source nova.gr
This does give data for the 18th but no earlier as we only reactivated this one again last week.
So it could be worth considering moving the load source , or at least doing a test load , once we have sufficient data , to the nova.gr downloads.
I will keep an eye on the nova.gr for a while and see if we do get these channel name variations and if our robot is picking them up.

**Comment by Lynne12** [comment]
FLMG is missing data for the following March 2021 dates:-
2,3,4,5,6,7

**Comment by Robinmcgvr** [comment]
Is that the case on the new source too?

**Comment by Lynne12** [comment]
I haven't looked. Your previous comment said you would be monitoring it.  At present ishow.gr is our primary loading source and I am reporting missing dates for that source.

**Comment by Robinmcgvr** [comment]
ok cheers I will check it out

**Comment by Robinmcgvr** [comment]
re. the march dates , yes we do have the data on nova.gr - unfortunately we only restarted pulling from this source after 19th Feb so it won't fill our other gaps

**Comment by Lynne12** [comment]
@Robinmcgvr novacinema1 finished on ishow.gr (Kablam) on 7th April 2021.  Do you know what the new name is for this channel?

**Comment by Lynne12** [comment]
> Thanks I have had a bit more of a look into this issue now, the constant loss of data for this channel 'Nova Cinema 1'.
> What I have found out is that a bit like Sky Movie channels there is a tendency for the channel to change its name seasonally or themed in some way. This would explain why it disappears from all sources simultaneously.
> Some good news and not necessarily explained by what I said above... is that we do have data from a newly revived source nova.gr
> This does give data for the 18th but no earlier as we only reactivated this one again last week.
> So it could be worth considering moving the load source , or at least doing a test load , once we have sufficient data , to the nova.gr downloads.
> I will keep an eye on the nova.gr for a while and see if we do get these channel name variations and if our robot is picking them up.

@Robinmcgvr shall we now change to this source, due to the continual problems with ishow.gr?

**Comment by Robinmcgvr** [comment]
sounds like a good idea

**Comment by Lynne12** [comment]
I will load 2-7 March, from nova.gr.
