### ISSUE TITLE
mi.tv brazil

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#66]
@JonathanETS 
Have requested Matteo add the channels BAND,SBT, GLOBO , REDE TV, RECORD and GAZETA (if he can find it)

**Comment by Lynne12** [comment]
@Robinmcgvr is there an update on this?

**Comment by Robinmcgvr** [comment]
@Lynne12 
yes what could be found was done. There was a bit of confusion about which Gazeta vsn we wanted, but it's available in Kablam now
