### ISSUE TITLE
Thailand - tvsmagazine

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#67]
@GoodallE 
@Ma-rco 
We are  missing some data from site tvsmagazine for 04/02/2021
Hope that's not too much of a problem

**Comment by GoodallE** [comment]
On 2021-02-15 11:20, Robinmcgvr wrote:
> Assigned #67 to @GoodallE.
No we don't really get much on here anyway. So if anything it should 
follow a pattern.

Thanks

Emma
