### ISSUE TITLE
HK now-tv.com

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#7]
We currently have data missing from beginning of Feb for this site - hopefully Matteo will be able to recover it.
Or we may need to look for alternative source.

**Comment by Lynne12** [comment]
@Robinmcgvr any news from Matteo on the recovery?  I am showing 11-14 February missing in the latest week of Online Scheduling.

**Comment by Robinmcgvr** [comment]
Unfortunately it was not possible to recover this data - which means there is a gap all the way from 3rd to 14rh Feb

**Comment by Robinmcgvr** [comment]
Fox Movies is available from foxmovies.asia which we do have downloads for

**Comment by Robinmcgvr** [comment]
Also available from epg.i-cable.com - this actually covers all the channels we would normally get from now-tv.com , so that is good news

**Comment by Lynne12** [comment]
> Unfortunately it was not possible to recover this data - which means there is a gap all the way from 3rd to 14rh Feb

Both channels are missing 3-17th February, which is as far as I have loaded the data.

**Comment by Lynne12** [comment]
I have asked Richard to set up the loader for the epg.i-cable.com, so I can load the data to fill the gaps in the channels.

**Comment by Lynne12** [comment]
Data loader to cover the gaps.

**Comment by Lynne12** [comment]
@Robinmcgvr reopening this, as Pavle has reported a problem with the data on STAR WORLD and STAR MOVIES.  I am liasing with Richard accordingly.

**Comment by Robinmcgvr** [comment]
@Lynne12 
Could you also let me know what the issue is please?

**Comment by Robinmcgvr** [comment]
@Lynne12 
I can confirm that the raw kapow data is all good - as is the kablam
n.b. Star Movies = Fox Movies
Star World = Fox Life 
In case that is what is causing the problem, but it is more likely to be overlapping data from the two loading sources . 
That may or may not be useful, but that is what I can contribute.

**Comment by Lynne12** [comment]
#914 on ETS Issues has the details.

**Comment by Lynne12** [comment]
@Robinmcgvr data now loaded, if you wish to close this issue.

**Comment by Lynne12** [comment]
@Robinmcgvr now-tv.com has been a problem for the March 2020 data, so I am now moving these channels to the epg.i-cable.com website going forwards.
