### ISSUE TITLE
Belgium - cinetelerevue.be 

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#72]
Data for 3-22 March currently missing - Matteo notified

**Comment by Robinmcgvr** [comment]
@Lynne12 
Update on this site:
Site is down for now due to a fire at the webhost acc. their website
They have set up a temporary service for now , I will see if Matteo can pull this data

**Comment by Robinmcgvr** [comment]
N.b this is also affecting moustique.be but they are only offering a digital version of their magazine

**Comment by Robinmcgvr** [comment]
Latest from Matteo re. Moustique and Cinetelerevue is that the data they are offering at the moment is from the tv-programme.telecablesat.fr site.
They are working on restoring the servers and hope to have this under way from the 22nd March.
So we will have to see how things are by then.

**Comment by Robinmcgvr** [comment]
Still affected by the fire

**Comment by Lynne12** [comment]
@Robinmcgvr any update on this please?

**Comment by Lynne12** [comment]
@Robinmcgvr are you able to provide an update on this please?

**Comment by Robinmcgvr** [comment]
@Lynne12 
data there in kablam
