### ISSUE TITLE
Greece Ishow

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#73]
I show Greece has missing data covering 6& 7 March - Matteo notified

**Comment by Robinmcgvr** [comment]
6 lost , 7th recovered , site still has missing data 18-21 March too

**Comment by Lynne12** [comment]
7th March data loaded

**Comment by Robinmcgvr** [comment]
18-21 March now recovered

**Comment by Robinmcgvr** [comment]
7-19 April missing

**Comment by Robinmcgvr** [comment]
We are having further issues with ishow - potential ones 
Matteo is having some problems with the way the channels are labelled on the site now, they are using graphics or flash for the logo.
He has tried something he hopes will make it work - but he is not sure it will.
We may have to consider not using this as the main download source.

**Comment by Robinmcgvr** [comment]
He has though recovered data back to 14th April

**Comment by Robinmcgvr** [comment]
re assignation, there was a problem with, or there appeared to be, you receiving messages from me via github a couple of months back so I make sure we are both assigned to everything to prevent that from happening again.

**Comment by Lynne12** [comment]
Data loaded, 14-19 April 2021
