### ISSUE TITLE
France-tv-programme.telecablesat.fr

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#76]
@Robinmcgvr the above is missing the following dates:-

10-15 March 2021

**Comment by Robinmcgvr** [comment]
Hopefully we'll get this data back once the servers are restored

**Comment by Robinmcgvr** [comment]
If we are still stuck for data after their recovery or before if needed, most channels are available from programme-television.org
inc. AB3

**Comment by Robinmcgvr** [comment]
this site is still affected by the fire

**Comment by Lynne12** [comment]
@Robinmcgvr any update on this please?

**Comment by Lynne12** [comment]
@Robinmcgvr are you able to provide an update on this missing data, please?

**Comment by Lynne12** [comment]
> Hopefully we'll get this data back once the servers are restored

@Robinmcgvr you closed this, without update.  There is still no data on Kablam, for this website.  Will it be recovered?

**Comment by Robinmcgvr** [comment]
@Lynne12 
What was able to be recovered was recovered, and is in kapow - I see the file sizes are smaller for that mid march period so we may be missing some channels.

**Comment by Lynne12** [comment]
All channels missing date found on the following websites:-

programme-television.org & programme-tv.net

**Comment by Robinmcgvr** [comment]
16-23 March never loaded for Teva
Missing data for Teva was available from programme-television.org - this doesn't seem to have been loaded for some reason
Now having to manually add this - 
Obv this goes back to the above issues, but we have still ended up with gaps in data when we had stuff to fill it - nause

**Comment by Robinmcgvr** [comment]
16-23 March never loaded for Teva

**Comment by Robinmcgvr** [comment]
Can we get the data loaded from programme-television.org?
I can process it, saves time rather than manually scheduling it all.

**Comment by Robinmcgvr** [comment]
Paris Premiere also needs loading 16-23 March

**Comment by Robinmcgvr** [comment]
Serie Club can be loaded from programme-tv.net for 16-22 March inclusive

**Comment by Robinmcgvr** [comment]
Cine Cine Premier (cinc) (Cine + premier) also needs loading for 16-22 March

**Comment by Robinmcgvr** [comment]
Cinf - Cine+ Classic also

**Comment by Robinmcgvr** [comment]
OK those are the channels most urgently required for the BMI report
I guess this may also affect the other sched channels and maybe data like Belgium etc affected too - this dates back to the issues with the web hosting fire and time taken for sites to be  restored I know.
I won;t keep putting individual details of any more channels here , I will combine so you aren't bombarded with lots more messages.
I don't think anyone else can get this stuff loaded, and you would probably prefer that they don't.
