### ISSUE TITLE
Hungary - tvmustra.hu

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#8]
@Robinmcgvr missing dates for HBO channel, 13,14,15 March 2020

**Comment by Robinmcgvr** [comment]
@Lynne12 
I have already flagged those days as Missing with Matteo but looks like they weren't recoverable -so we will have to look at our other hungarian downloads , sorry

**Comment by Robinmcgvr** [comment]
@Lynne12 
There are downloads from hbo.hu in kapow

**Comment by Lynne12** [comment]
Missing dates loaded from hbo.hu
