### ISSUE TITLE
Sweden tv-table.se

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#80]

**Comment by Lynne12** [comment]
Why have you assigned me here Robin?

**Comment by Robinmcgvr** [comment]
@Lynne12 
It's one of back up sources for sweden 
Thought you might want to know ...

**Comment by Lynne12** [comment]
You haven't put anything in the description box.  You have just opened the issue with a subject and the box for the description of the issue is empty.

**Comment by Robinmcgvr** [comment]
oh yeah! 16-22 March affected

**Comment by Lynne12** [comment]
> @Lynne12
> It's one of back up sources for sweden
> Thought you might want to know ...

It's a main source for online loading for channels CSF1, CSF2

**Comment by Robinmcgvr** [comment]
Data still missing from tv-tabla.se cannot be recovered pre 26/03 - but data is available from Viasat.se

**Comment by Lynne12** [comment]
Data on Kablam starts from 27th March.  16-26 March loaded from Viasat.se, to fill the gaps on CSF1 & CSF2

**Comment by Lynne12** [comment]
@Robinmcgvr can this be closed, pleased.  The missing data has been loaded.
