### ISSUE TITLE
Romania online scheduling - a1.ro

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#82]
@Robinmcgvr above website is missing 31 March - 12 April 2021

**Comment by Robinmcgvr** [comment]
Thanks, yep I am aware and it has been reported to Matteo

**Comment by Robinmcgvr** [comment]
@Lynne12 
Downloads for this site are still failing and we are unable to go back on the site.
So we will have to use an alternative loading source until the robot for this one is fixed - if that is actually possible to do.

**Comment by Lynne12** [comment]
Data 31 March - 12 April 2021 has been loaded from program24.ro

**Comment by Lynne12** [comment]
@Robinmcgvr please can you close this, as the missing data has been loaded.
