### ISSUE TITLE
Switzerland-teleclub.ch

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#83]
@Robinmcgvr 15th April is missing for the above site.  This relates to channels TCBZ=blue Prime and TCBS=blue Action

**Comment by Robinmcgvr** [comment]
Thanks Lynne, a case of where we have the day's data but not the channel we want, so it doesn;t get spotted by the kapow check.
The data is still available on the site so I will see if Matteo is able to recover it for us.

**Comment by Robinmcgvr** [comment]
Unfortunately Matteo did not manage to recover the data from teleclub.ch in time
BUT we do have the data in the tv.search.ch downloads as 'Teleclub Action' and 'Teleclub Prime'

**Comment by Lynne12** [comment]
@Robinmcgvr you don't need to keep assigning me on this.  I created the issue, so I will always receive an update when a new entry is added.

**Comment by Robinmcgvr** [comment]
re assignation, there was a problem with, or there appeared to be, you receiving messages from me via github a couple of months back so I make sure we are both assigned to everything to prevent that from happening again.

**Comment by Lynne12** [comment]
I don't recall never receiving messages from you.  The creator of the issue will always see updates, so no need to assign me, if I have created the issue.  I get emails for all issues, on all repositories.

**Comment by Lynne12** [comment]
15th April loaded from tv.search.ch
