### ISSUE TITLE
OPR SITES - FOX.TV.NO & LA.AXN.COM

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#84]
There are problems with the above sites which I have listed as being ones used for OPR
Foxtv.no now redirects to disney plus 
la.axn.com has changed the format on the site which makes it tricky to pull anything other than Mexico data and even that doesn't seem to be working.
If this is one you particularly need, I will ask Matteo to do some more work on trying to restore it.

**Comment by GoodallE** [comment]
On 2021-04-26 10:54, Robinmcgvr wrote:
> Assigned #84 to @GoodallE.
we have mi.tv site for LA  so that should be ok and for Norway there we 
do rely on fox site for OPR if the data doesn't come in with episodes 
on.

Thanks

Emma

**Comment by Robinmcgvr** [comment]
I think actually that channel Fox Norway has ceased, awaiting confirmation on this

**Comment by Robinmcgvr** [comment]
Yes channel ceased
