### ISSUE TITLE
Switzerland: teleclub.ch

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#86]
@Robinmcgvr the above website is missing 14th May, used for Teleclub and Teleclub Star.

**Comment by Robinmcgvr** [comment]
@Lynne12 
site is there , but seems the channels are missing unfortunately

**Comment by Robinmcgvr** [comment]
Have asked Matteo if he can add the data for those two channels, if not we do have back up source.

**Comment by Robinmcgvr** [comment]
Matteo was only able to recover the data from 15:00 onwards - earlier part of the day could be manually scheduled via tvsearch.ch

**Comment by Lynne12** [comment]
@Robinmcgvr **tvsearch.ch does not have Teleclub Star on**.  I have manually scheduled Teleclub from tvsearch.ch. I will load both channels, from 15.00 from teleclub.ch.

**Comment by Robinmcgvr** [comment]
Teleclub star = Teleclub Action on tvsearch

**Comment by Lynne12** [comment]
Teleclub Star manually scheduled from tvsearch.ch.
