### ISSUE TITLE
Switzerland - rts.ch

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#89]
@Robinmcgvr this website is missing date for 15-20 June, for the ETS channels, TSI1 and TSI2.

**Comment by Robinmcgvr** [comment]
Thanks, we should be covered by other sources if this isn't recoverable

**Comment by Robinmcgvr** [comment]
Hi Lynne that data is not going to be recoverable , it is not on the site for those dates.
We do have the channels covered by rsi.ch , so you will need to load that week from that site.
rts.ch looks ok after that.

**Comment by Lynne12** [comment]
Data loaded, to fill gaps, from rsi.ch
