### ISSUE TITLE
Sweden - tv.nu

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#9]
@Robinmcgvr 

We load the channels CSF1 (CMoreFirst), CSF2 (CMoreHits) and TV1000 (Viasat Film Premiere), from tv.nu, for online scheduling.  All 3 of these channels stopped on Kablam in the early hours of 14th March.  Is this something you have addressed with Matteo?

**Comment by Robinmcgvr** [comment]
@Lynne12 
Hi Lynne, no I was not aware of the issue as my checks only look to see that we are downloading from the site , it doesn't pick up if channels are missing - I will email Matteo about it now .
We can get viasat film premiere from viasat.se and the Cmore channels from tv4.se if Matteo is unable to recover the data from tv.nu 
Looking at the tv.nu site, it looks like data will go back to 15/03 BUT it doesn't seem as easy to get listings for Cmore First anymore, hopefully we can get it sorted out though.
Thanks for letting me know.

**Comment by Robinmcgvr** [comment]
@Lynne12 

Bad news we are no longer able to grab Kanal 10, Viasat film premiere, nor the two Cmore channels, for that source - but at least we have them from the sources I mentioned previously

Sorry first version of this reply was nonsense!

**Comment by Lynne12** [comment]
@Robinmcgvr thanks.  I will change the loading sources with Richard.
