### ISSUE TITLE
Portugal - nos.pt

### ISSUE THREAD

**Issue by Lynne12** [Robinmcgvr/Kapow-Data#92]
@Robinmcgvr the above website is missing 19th July 2021

**Comment by Robinmcgvr** [comment]
@Lynne12 
Oh dear that one slipped through the net and won't go back that far , you'll have to use tv.sapo.pt to plug that gap I am afraid

**Comment by Lynne12** [comment]
Missing date loaded from sic.sapo.pt (SIC) and tv.sapo.pt (TVI), as these were already set up.
