### ISSUE TITLE
MIDDLE EAST MBC2 MBC ACTION

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#93]
Schedules for MBC2 and MBC Action have disappeared from both the elcinema.com and mbc.net sites as from the 26/07/2021
Nothing found on the internet about the channels having ceased or being rebranded.
Will need to keep checking this to see if the data comes back

**Comment by Lynne12** [comment]
@Robinmcgvr data for MBC2 resumed on 10th August and MBC Action on 12th August 2021

**Comment by Robinmcgvr** [comment]
MBC schedules finally back again, data seems to have restarted from August 12th ,although no downloads for MBC action for that date, but hopefully ok going forwards
