### ISSUE TITLE
mojtv.net-rs - SERBIA

### ISSUE THREAD

**Issue by Robinmcgvr** [Robinmcgvr/Kapow-Data#98]
We are missing two days from this source currently, 11th & 12th Sept - have asked Matteo to fix but we may lose a day or two

**Comment by Robinmcgvr** [comment]
This not been fixed yet - but is being worked on, there will be a lag on this data , but shouldn't really affect anything

**Comment by Lynne12** [comment]
@Robinmcgvr missing 19th & 20th September too.

**Comment by Robinmcgvr** [comment]
@Lynne12 
I will check this with Matteo, but there is a known issue with this site actively blocking us and Matteo is having to do a work around to pull the data from the source - the data usually appears a few days later

**Comment by Lynne12** [comment]
Dates have now appeared and have been loaded.

**Comment by Robinmcgvr** [comment]
N.B. This will be an ongoing thing, due to the way Matteo is having to deal with this data - so we can expect this site to be several days behind visibly for the foreseeable future.

**Comment by Lynne12** [comment]
For reference, data missing 30 September - 4 October

**Comment by Robinmcgvr** [comment]
This is to be expected as mentioned before

**Comment by Lynne12** [comment]
Data loaded 30 September - 4 October

**Comment by Lynne12** [comment]
Missing 9-11 October.

**Comment by Robinmcgvr** [comment]
we should get this data tomorrow -Matteo is having to do extra processes for this source

**Comment by Lynne12** [comment]
Missing 12,13,17,18 October.

**Comment by Lynne12** [comment]
> Missing 9-11 October.

Date range recovered and loaded.

**Comment by Robinmcgvr** [comment]
@Lynne12 
I am a bit confused about where you are getting this information from as in the kapow folder 9-14 still shows as missing
OK looked at this in kablam and I am getting data for e.g. Pink Premium for 9th and 10th , but these dates don't show up in kapow data - I think that what you have loaded is incorrect.
I am seeking more inf. from Matteo about this - but i suspect something has gone weird with kablam data

**Comment by Robinmcgvr** [comment]
@Lynne12 
I have deleted data from 'Kingsman' onwards starting 09/10 -11/10/2021
Only on Pink Premium at this point, but the other channels will all be wrong too

**Comment by Robinmcgvr** [comment]
If you are waiting on data and you haven't been informed that it has been recovered be cautious about going ahead and loading it.
I think this is a one off what has happened here with Kablam and thank goodness you did say you had loaded it.

**Comment by Lynne12** [comment]
@Robinmcgvr when there are gaps and the data is recovered it is always loaded from Kablam.  I have no way to pull and load it from any other source.  If you have another way then can I suggest that when data is recovered you load it and make a note here please.  This would apply to any country with data gaps and recovery.

**Comment by Robinmcgvr** [comment]
@Lynne12 
OK data is sorted
1) loaded data that I have checked looks ok (have undeleted)
2) data is now available to 19/10/2021 (inc) - you are clear to load to that date.
Hopefully we don't get any more cases of invisible data!
We will carry on having a lag with the data for Serbia though

**Comment by Lynne12** [comment]
@Robinmcgvr I need to know exactly what data you have deleted, for which channels.  I had loaded all channels to 16 October 2021, with the exception of 12 &13, which I notified you were missing, along with the 17 & 18 missing for this week.

**Comment by Robinmcgvr** [comment]
I undeleted the data for Pink Premium as I said above.

'@Lynne12
I have deleted data from '_Kingsman' onwards starting 09/10 -11/10/2021_
_Only on Pink Premium_ '

'OK data is sorted

loaded data that I have checked looks ok (have undeleted)
data is now available to 19/10/2021 (inc) - you are clear to load to that date.
Hopefully we don't get any more cases of invisible data!
We will carry on having a lag with the data for Serbia though'

**Comment by Lynne12** [comment]
> Missing 12,13,17,18 October.

data loaded.

**Comment by Robinmcgvr** [comment]
@Lynne12 
You are clear to load to 24/10/2021

**Comment by Robinmcgvr** [comment]
@Lynne12 
You are clear to load to 31/10/2021
we have data to 02/11/2021 - the few days lag will continue

**Comment by Lynne12** [comment]
Data missing 27-30 November.

**Comment by Robinmcgvr** [comment]
Thanks I reported this to Matteo monday - but as he hasn't fixed it yet I will give him a nudge

**Comment by Robinmcgvr** [comment]
@Lynne12 
More re serbia - i wouldn't attempt to load past the 15th November as the data files look very small.
I have raised this and asked Matteo to recover data back to the 16th

**Comment by Lynne12** [comment]
Data is already loaded to 26th November.

**Comment by Robinmcgvr** [comment]
Unfortunately there could be some big gaps so you may want to check that or delete it

**Comment by Lynne12** [comment]
Can we not look for another source for this?  This is becoming a weekly issue now and very time consuming.

**Comment by Robinmcgvr** [comment]
There is no pink premium from 17-20 in the current data, nor PInk family,
Matteo is having to do a lot of work on this data every week - I did warn that there would be issues with the data each week.
But yes it is becoming a big pain now, as have all the other sites we used to use for this.
I am working on reports at the moment so I don't have much time currently to search out new sources right now.
I will look at it next week.

**Comment by Robinmcgvr** [comment]
Although we now have full data for 24-29th Nov,  the small data files from 16-20 have not been boosted or had their full data recovered yet.
I emailed Matteo about this last week, and printed out data from site as a back up measure.

**Comment by Robinmcgvr** [comment]
Pink Family is available from one of our other sources , hence why have only printed out Pink Premium data
This came from our old source tvprofil but we were getting blocked from pulling data from the site, hence why that ceased.
I will also ask Matteo to see if that is still the case

**Comment by Lynne12** [comment]
For my reference, as there are a lot of messages on here now.   Missing dates, in Studio, as follows:-

PINK FAMILY - 16-22 November
PINK PREMIUM - 16-22 November

**Comment by Lynne12** [comment]
> For my reference, as there are a lot of messages on here now. Missing dates, in Studio, as follows:-
> 
> PINK FAMILY & PINK PREMIUM - 16-22 & 25-30 November RTV PINK - 27-30 November

Data recovered in Kablam and will now be loaded.

**Comment by Robinmcgvr** [comment]
Yeah you beat me to it there, just had notification from Matteo that the data was recovered.

**Comment by Lynne12** [comment]
Is the 16-22 recovered for the two channels above?

**Comment by Robinmcgvr** [comment]
yes it looks ok in kablam

**Comment by Lynne12** [comment]
All missing dates loaded.

**Comment by Lynne12** [comment]
@Robinmcgvr 1-6 December missing.

**Comment by Lynne12** [comment]
@Robinmcgvr 7-13 December missing.

**Comment by Robinmcgvr** [comment]
@Lynne12 
As you have probably seen I have both Matteo and Richard looking into issues with this data.
I have asked Matteo to try a couple of other sites.
In the meantime the only way to ensure we can plug the gap is to print out the data as I have been doing.
Pink Premium seems to be the only channel that isn't covered by any of our other sources , so that is the one I am focusing on.
The only other solution to this one would be to start making the channel be manually entered daily like some of our other channels, but given we are about to break up for xmas that change over is not timely right now.
It's a big pain but am doing all I can

**Comment by Lynne12** [comment]
@Robinmcgvr 19th & 20th December missing

**Comment by Robinmcgvr** [comment]
@Lynne12 
This is ok now - data available to 24/12
I have set up a new source, not yet available in Kablam , for channel Pink Premium and may add some others to it .
then we will probably drop mojtv.net-rs

**Comment by Lynne12** [comment]
Data missing 25th December 2021 - 3 January 2022

**Comment by Robinmcgvr** [comment]
As said above data only ready to 24/12
We can cover from our other sources
New site telegraf.rs now in kablam - covering Pink Premium from 24/12 to 05/01 
Have asked Matteo to expand the source going forwards to cover all Pink channels, the only one we can't get from here is Pink2
We are going to drop mojtv site

**Comment by Lynne12** [comment]
I will wait to hear when all is ready at Matteo's end, so that I can set the new source up for all channels that it will cover.  Will also wait for a replacement website for Pink2.

**Comment by Robinmcgvr** [comment]
I thought we loaded Pink2 from extratv.me?

**Comment by Lynne12** [comment]
> I thought we loaded Pink2 from extratv.me?
Yes, we do.  You confused me by mentioning on here, when this relates to mojtv channels.

**Comment by Robinmcgvr** [comment]
Ok I think i was just confirming that we couldn't get it from the new source. So we unfortunately can't use a single source for all channels, which would have been nice

**Comment by Robinmcgvr** [comment]
@Lynne12 
mojtv.net-rs data now available to 29/12

**Comment by Robinmcgvr** [comment]
we  have to 05/01/2022 in kapow, but this has not made it to kablam yet - will chase up if not there by next week

**Comment by Robinmcgvr** [comment]
re this data, I suppose if we use the mojtv data to the end of 2021 and then start with telegraf.rs thereafter?

**Comment by Lynne12** [comment]
@Robinmcgvr I have pulled files, in Atelier, this morning and the following is still missing:-

1-12 December
25-28 December

**Comment by Lynne12** [comment]
The following missing dates have been loaded:-

13, 19, 20, 29, 30, 31 December 2021
1-3 January 2022

**Comment by Robinmcgvr** [comment]
@Lynne12 
I am not sure what is going on here, I have pulled 1-12 and 25-28 december for Pink Premium from mojtv.net in Kablam just now

**Comment by Robinmcgvr** [comment]
Can you try loading that data again please?
If it still doesn't work I will raise with Matteo and Richard
I am able to pull all dates up to 06/01/2022 so there is something else going on here

**Comment by Lynne12** [comment]
The dates were not in the files when I pulled them, so it would be pointless me trying to load them again, as unless they have appeared in the last hour they will still not be in the Atelier download.

**Comment by Robinmcgvr** [comment]
I am looking at the data right now.
I am referring this to Richard and Matteo to sort out.

**Comment by Lynne12** [comment]
6-10 January 2022 missing.

**Comment by Robinmcgvr** [comment]
Not having any joy getting the issues with this resolved.
I think the best thing is to switch to the new source telegraf.rs immediately and then we don't have to mess about with this data any more.

**Comment by Lynne12** [comment]
Data is only available on telegraf.rs from 11th January 2022.
Just to confirm is this website switch just for the following channels?:-
PINK FAMILY
PINK PREMIUM
PINK

**Comment by Lynne12** [comment]
> @Robinmcgvr I have pulled files, in Atelier, this morning and the following is still missing:-
> 
> 1-12 December 25-28 December

I've now been able to pull these dates from Kablam and load them.  6-10 January 2022 is still not available in Kablam, but I will keep an eye on this.  
Will just wait for the above confirmation and then switch the loading source.

**Comment by Robinmcgvr** [comment]
OK we have pink premium in kablam from 25/12 to 11/01 
I can see and pull this data - so you should be able to use telegraf to load Pink Premium and then don't need to mess about with mojtv.net

Pink Film and Pink were added later as they were not ones we were having problems with , but i thought it would be useful to have them available from telegraf.rs
So from 11/01 onwards data you can potentially load all three of those channels from new source.
Anyway - abandon using mojtv.net is my advice.

**Comment by Robinmcgvr** [comment]
n.b. to confirm the data for Pink Premium is available via telegraf.rs from 25/12 to 11/01

**Comment by Robinmcgvr** [comment]
sorry for some reason i had in my mind that it was only Pink Premium you were pulling from moj.
But it was that we already had the alternative source of tv.aladdin.info for Family and Kids, so that was why I was prioritising Premium channel

**Comment by Lynne12** [comment]
> 6-10 January 2022 missing.

6-10 January 2022 now loaded from mojtv.net-rs

**Comment by Lynne12** [comment]
Loading source now being changed to telegraf.rs
